### ISSUE TITLE
Bug: PermissionError: [Errno 13] Permission denied: '/Users/nathan'

### ISSUE THREAD

**Issue by bern-dog** [nathom/streamrip#104]
I get this when trying to rip from deezer. Any ideas? Appreciate your work as always

EDIT: also happened with Qobuz
```
streamrip is up-to-date!
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/bin/rip", line 8, in <module>
    sys.exit(main())
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/streamrip/cli.py", line 415, in main
    cli(obj={})
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/click/core.py", line 1646, in invoke
    super().invoke(ctx)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/streamrip/cli.py", line 117, in cli
    core.download()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/streamrip/core.py", line 251, in download
    item.download(**arguments)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/streamrip/bases.py", line 831, in download
    self._prepare_download(**kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/streamrip/tracklists.py", line 113, in _prepare_download
    os.makedirs(self.folder, exist_ok=True)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/os.py", line 215, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/os.py", line 215, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/os.py", line 225, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/Users/nathan'
```

**Comment by BobRock55** [comment]
Change download location to match your configuration. 

Here is how I corrected the problem, however this should not be happening. 

[downloads]
# Folder where tracks are downloaded to
#folder = "/Users/nathan/StreamripDownloads"
folder = "/home/xxxxx/StreamripDownloads"
