### ISSUE TITLE
Bug :crash when the track is not available for download 

### ISSUE THREAD

**Issue by Xmetalfire2** [nathom/streamrip#108]
when i try to download this track the program says it is not available, i know why its doing that but instead of skipping the program crashes

`streamrip is up-to-date!
Extracting IDs from Deezer dynamic link. Use urls of the form https://www.deezer.com/{country}/{type}/{id} for faster processing.

Downloading Loved Tracks (Playlist)

Downloading "Pink Floyd - Another Brick In The Wall, Pt. 2 (2011 Remastered Version)"
Cover: 100%|█████████████████████████████████████████████████████████████████████| 14.7k/14.7k [00:00<00:00, 15.2MiB/s]
Track 01: 100%|██████████████████████████████████████████████████████████████████| 23.8M/23.8M [00:01<00:00, 12.6MiB/s]

Downloading "David Bowie - Life on Mars? (2015 Remaster)"
Cover: 100%|█████████████████████████████████████████████████████████████████████████████| 15.0k/15.0k [00:00<?, ?iB/s]
Track David Bowie - Life on Mars? (2015 Remaster) is not available for download, skipping.
Traceback (most recent call last):
  File "c:\users\tom\appdata\local\programs\python\python39-32\lib\site-packages\mutagen\_util.py", line 251, in _openfile
    fileobj = open(filename, "rb+" if writable else "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\tom\\AppData\\Local\\Temp\\107474522_2.tmp'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\tom\appdata\local\programs\python\python39-32\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\tom\appdata\local\programs\python\python39-32\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\tom\AppData\Local\Programs\Python\Python39-32\Scripts\rip.exe\__main__.py", line 7, in <module>
  File "c:\users\tom\appdata\local\programs\python\python39-32\lib\site-packages\streamrip\cli.py", line 415, in main
    cli(obj={})
  File "c:\users\tom\appdata\local\programs\python\python39-32\lib\site-packages\click\core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\tom\appdata\local\programs\python\python39-32\lib\site-packages\click\core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "c:\users\tom\appdata\local\programs\python\python39-32\lib\site-packages\click\core.py", line 1646, in invoke
    super().invoke(ctx)
  File "c:\users\tom\appdata\local\programs\python\python39-32\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\tom\appdata\local\programs\python\python39-32\lib\site-packages\click\core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "c:\users\tom\appdata\local\programs\python\python39-32\lib\site-packages\click\decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "c:\users\tom\appdata\local\programs\python\python39-32\lib\site-packages\streamrip\cli.py", line 117, in cli
    core.download()
  File "c:\users\tom\appdata\local\programs\python\python39-32\lib\site-packages\streamrip\core.py", line 257, in download
    item.download(**arguments)
  File "c:\users\tom\appdata\local\programs\python\python39-32\lib\site-packages\streamrip\bases.py", line 861, in download
    target(item, **kwargs)
  File "c:\users\tom\appdata\local\programs\python\python39-32\lib\site-packages\streamrip\tracklists.py", line 492, in _download_item
    audio = FLAC(item.path)
  File "c:\users\tom\appdata\local\programs\python\python39-32\lib\site-packages\mutagen\_file.py", line 48, in __init__
    self.load(*args, **kwargs)
  File "c:\users\tom\appdata\local\programs\python\python39-32\lib\site-packages\mutagen\_util.py", line 185, in wrapper
    return func(*args, **kwargs)
  File "c:\users\tom\appdata\local\programs\python\python39-32\lib\site-packages\mutagen\_util.py", line 154, in wrapper
    with _openfile(self, filething, filename, fileobj,
  File "c:\users\tom\appdata\local\programs\python\python39-32\lib\contextlib.py", line 117, in __enter__
    return next(self.gen)
  File "c:\users\tom\appdata\local\programs\python\python39-32\lib\site-packages\mutagen\_util.py", line 272, in _openfile
    raise MutagenError(e)
mutagen.MutagenError: [Errno 2] No such file or directory: 'C:\\Users\\tom\\AppData\\Local\\Temp\\107474522_2.tmp'
`

**Comment by nathom** [comment]
Please send the link you used.

**Comment by Xmetalfire2** [comment]
https://deezer.page.link/yAFpmmBKJWGdqoLLA

**Comment by nathom** [comment]
Fixed in `v0.6.5`
