### ISSUE TITLE
Bug: TypeError: '<' not supported between instances of 'int' and 'NoneType'

### ISSUE THREAD

**Issue by tikilab** [nathom/streamrip#110]
## Bug Report

**Current Behavior**

Error on attempted download, no files created.

**Command used:**

```bash
# rip -u https://tidal.com/browse/album/182104866
```

**Expected behavior**

Successful download.

**`streamrip` Configuration File (find using `rip config -o`):**

```toml
[downloads]
# Folder where tracks are downloaded to
folder = "/Volumes/04 iTunes Beach SATA 4TB/StreamRip"
# Put Qobuz albums in a 'Qobuz' folder, Tidal albums in 'Tidal' etc.
source_subdirectories = true
# Download (and convert) tracks all at once, instead of sequentially. 
# If you are converting the tracks, or have fast internet, this will 
# substantially improve processing speed.
concurrent = true
[qobuz]
# 1: 320kbps MP3, 2: 16/44.1, 3: 24/<=96, 4: 24/>=96
quality = 4
# This will download booklet pdfs that are included with some albums
download_booklets = true
email = ""
# This is an md5 hash of the plaintext password
password = ""
# Do not change
app_id = ""
# Do not change
secrets = []
[tidal]
# 0: 256kbps AAC, 1: 320kbps AAC, 2: 16/44.1 "HiFi" FLAC, 3: 24/44.1 "MQA" FLAC
quality = 3
# This will download videos included in Video Albums.
download_videos = true
# Doesn't require login
[deezer]
# 0, 1, or 2
quality = 2
[soundcloud]
# Only 0 is available for now
quality = 0
[youtube]
# Only 0 is available for now
quality = 0
# Download the video along with the audio
download_videos = false
# The path to download the videos to
video_downloads_folder = ""
# This stores a list of item IDs so that repeats are not downloaded.
[database]
enabled = true
path = "/Users/donuthole/Library/Application Support/streamrip/downloads.db"
# Convert tracks to a codec after downloading them.
[conversion]
enabled = false
# FLAC, ALAC, OPUS, MP3, VORBIS, or AAC
codec = "ALAC"
# In Hz. Tracks are downsampled if their sampling rate is greater than this. 
# Value of 48000 is recommended to maximize quality and minimize space
sampling_rate = 48000
# Only 16 and 24 are available. It is only applied when the bit depth is higher
# than this value.
bit_depth = 24
# Filter a Qobuz artist's discography. Set to 'true' to turn on a filter.
[filters]
# Remove Collectors Editions, live recordings, etc.
extras = false
# Picks the highest quality out of albums with identical titles.
repeats = false
# Remove EPs and Singles
non_albums = false
# Remove albums whose artist is not the one requested
features = false
# Skip non studio albums
non_studio_albums = false
# Only download remastered albums
non_remaster = false
[artwork]
# Write the image to the audio file
embed = false
# The size of the artwork to embed. Options: thumbnail, small, large, original.
# "original" images can be up to 30MB, and may fail embedding. 
# Using "large" is recommended.
size = "large"
# Save the cover image at the highest quality as a seperate jpg file
keep_hires_cover = true
[metadata]
# Sets the value of the 'ALBUM' field in the metadata to the playlist's name. 
# This is useful if your music library software organizes tracks based on album name.
set_playlist_to_album = true
# Replaces the original track's tracknumber with it's position in the playlist
new_playlist_tracknumbers = true
# Changes the folder and file names generated by streamrip.
[filepaths]
# Create folders for single tracks within the downloads directory using the folder_format
# template
add_singles_to_folder = false
# Available keys: "albumartist", "title", "year", "bit_depth", "sampling_rate",
# and "container"
folder_format = "{albumartist} - {title} ({year}) [{container}] [{bit_depth}B-{sampling_rate}kHz]"
# Available keys: "tracknumber", "artist", "albumartist", "composer", and "title"
track_format = "{tracknumber}. {artist} - {title}"
# Last.fm playlists are downloaded by searching for the titles of the tracks
[lastfm]
# The source on which to search for the tracks.
source = "qobuz"
# If no results were found with the primary source, the item is searched for 
# on this one.
fallback_source = "deezer"
[misc]
# Check whether a newer version of streamrip is available when starting up
check_for_updates = true
# Metadata to identify this config file. Do not change.
version = "0.6.1"
```

**Environment**

- `streamrip` version(s): 0.6.7
- Python version: 3.9.5
- OS: OSX 10.14.6

**Traceback**
```bash
Traceback (most recent call last):
  File "/Users/donuthole/.pyenv/versions/3.9.5/bin/rip", line 8, in <module>
    sys.exit(main())
  File "/Users/donuthole/.pyenv/versions/3.9.5/lib/python3.9/site-packages/streamrip/cli.py", line 415, in main
    cli(obj={})
  File "/Users/donuthole/.pyenv/versions/3.9.5/lib/python3.9/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/Users/donuthole/.pyenv/versions/3.9.5/lib/python3.9/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/Users/donuthole/.pyenv/versions/3.9.5/lib/python3.9/site-packages/click/core.py", line 1646, in invoke
    super().invoke(ctx)
  File "/Users/donuthole/.pyenv/versions/3.9.5/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/donuthole/.pyenv/versions/3.9.5/lib/python3.9/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/Users/donuthole/.pyenv/versions/3.9.5/lib/python3.9/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/donuthole/.pyenv/versions/3.9.5/lib/python3.9/site-packages/streamrip/cli.py", line 117, in cli
    core.download()
  File "/Users/donuthole/.pyenv/versions/3.9.5/lib/python3.9/site-packages/streamrip/core.py", line 257, in download
    item.download(**arguments)
  File "/Users/donuthole/.pyenv/versions/3.9.5/lib/python3.9/site-packages/streamrip/bases.py", line 831, in download
    self._prepare_download(**kwargs)
  File "/Users/donuthole/.pyenv/versions/3.9.5/lib/python3.9/site-packages/streamrip/tracklists.py", line 111, in _prepare_download
    self.folder = self._get_formatted_folder(
  File "/Users/donuthole/.pyenv/versions/3.9.5/lib/python3.9/site-packages/streamrip/tracklists.py", line 279, in _get_formatted_folder
    formatted_folder = clean_format(self.folder_format, self._get_formatter())
  File "/Users/donuthole/.pyenv/versions/3.9.5/lib/python3.9/site-packages/streamrip/tracklists.py", line 242, in _get_formatter
    stats = tuple(
  File "/Users/donuthole/.pyenv/versions/3.9.5/lib/python3.9/site-packages/streamrip/tracklists.py", line 243, in <genexpr>
    min(bd, sr)
TypeError: '<' not supported between instances of 'int' and 'NoneType'
```

**Possible Solution**
Not sure but it was working before I did the last upgrade a few days ago.

**Comment by nathom** [comment]
Hmm... I can't reproduce this error. The album is downloading fine for me. Try resetting the config with `rip config --reset` and run the command again.

**Comment by tikilab** [comment]
OK, resetting the config did not work. I also tried uninstalling completely and reinstalling, and I am getting the identical error.

**Comment by nathom** [comment]
Can you run `rip -u https://tidal.com/browse/album/182104866 --debug >> streamrip_110.log` and send the file named `streamrip_110.log`?

**Comment by tikilab** [comment]
Oddly audio rips are now working perfectly which is really confusing me since I haven't changed anything since yesterday.

[streamrip_110.log](https://github.com/nathom/streamrip/files/6758212/streamrip_110.log)
Video rips however, are now producing errors:

`# rip -u https://tidal.com/browse/video/24692161`

```
streamrip is up-to-date!
Logged into Tidal
Traceback (most recent call last):
  File "/Users/donuthole/.pyenv/versions/3.9.5/bin/rip", line 8, in <module>
    sys.exit(main())
  File "/Users/donuthole/.pyenv/versions/3.9.5/lib/python3.9/site-packages/streamrip/cli.py", line 415, in main
    cli(obj={})
  File "/Users/donuthole/.pyenv/versions/3.9.5/lib/python3.9/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/Users/donuthole/.pyenv/versions/3.9.5/lib/python3.9/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/Users/donuthole/.pyenv/versions/3.9.5/lib/python3.9/site-packages/click/core.py", line 1646, in invoke
    super().invoke(ctx)
  File "/Users/donuthole/.pyenv/versions/3.9.5/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/donuthole/.pyenv/versions/3.9.5/lib/python3.9/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/Users/donuthole/.pyenv/versions/3.9.5/lib/python3.9/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/donuthole/.pyenv/versions/3.9.5/lib/python3.9/site-packages/streamrip/cli.py", line 117, in cli
    core.download()
  File "/Users/donuthole/.pyenv/versions/3.9.5/lib/python3.9/site-packages/streamrip/core.py", line 252, in download
    item.load_meta(**arguments)
TypeError: load_meta() got an unexpected keyword argument 'database'

```
