### ISSUE TITLE
Bug: TypeError: load_meta() got an unexpected keyword argument 'database'

### ISSUE THREAD

**Issue by lua-latex** [nathom/streamrip#112]
## Bug Report

**Current Behavior**
Attempts to download music are met with an error.

**Command used:**

```bash
rip -u 'https://www.deezer.com/us/track/1395565972'
```

**Expected behavior**
Should've downloaded the track as normal, encountered a syntax error instead.

**`streamrip` Configuration File (find using `rip config -o`):**

```toml
[downloads]
folder = "/home/nu/med/mus/"
source_subdirectories = false
concurrent = false

[qobuz]
quality = 3
download_booklets = true
email = ""
password = ""
app_id = ""
secrets = []

[tidal]
quality = 3
download_videos = true

user_id = ""
country_code = ""
access_token = ""
refresh_token = ""
token_expiry = ""

[deezer]
quality = 1

[soundcloud]
quality = 0

[youtube]
quality = 0
download_videos = false
video_downloads_folder = ""

[database]
enabled = true
path = "/home/nu/etc/streamrip/downloads.db"

[conversion]
enabled = false
codec = "ALAC"
sampling_rate = 48000
bit_depth = 24

[filters]
extras = false
repeats = false
non_albums = false
features = false
non_studio_albums = false
non_remaster = false

[artwork]
embed = true
size = "large"
keep_hires_cover = true

[metadata]
set_playlist_to_album = true
new_playlist_tracknumbers = true

[filepaths]
add_singles_to_folder = false
folder_format = "{albumartist} - {title} ({year}) [{container}] [{bit_depth}B-{sampling_rate}kHz]"
track_format = "{tracknumber}. {artist} - {title}"

[lastfm]
source = "qobuz"
fallback_source = "deezer"

[misc]
check_for_updates = true
version = "0.6.1"

[path_format]
folder = "{albumartist} - {title} ({year}) [{container}] [{bit_depth}B-{sampling_rate}kHz]"
track = "{tracknumber}. {artist} - {title}"
```

**Environment**

- `streamrip` version(s): 0.6.7
- Python version: 3.9
- OS: Arch Linux

**Traceback**
```bash
Traceback (most recent call last):
  File "/home/nu/var/python/bin//rip", line 8, in <module>
    sys.exit(main())
  File "/home/nu/var/python/lib/python3.9/site-packages/streamrip/cli.py", line 415, in main
    cli(obj={})
  File "/home/nu/var/python/lib/python3.9/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/home/nu/var/python/lib/python3.9/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/home/nu/var/python/lib/python3.9/site-packages/click/core.py", line 1646, in invoke
    super().invoke(ctx)
  File "/home/nu/var/python/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/nu/var/python/lib/python3.9/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/home/nu/var/python/lib/python3.9/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/nu/var/python/lib/python3.9/site-packages/streamrip/cli.py", line 117, in cli
    core.download()
  File "/home/nu/var/python/lib/python3.9/site-packages/streamrip/core.py", line 252, in download
    item.load_meta(**arguments)
TypeError: load_meta() got an unexpected keyword argument 'database'
```

**Additional context/Screenshots**
This occurred after applying the latest update to streamrip, afaik I was only one version behind so perhaps the latest release caused it?

**Comment by nathom** [comment]
This will be fixed in the next version. Use the album link (`https://www.deezer.com/us/album/235291132`) for now.

**Comment by lua-latex** [comment]
ah ight
