### ISSUE TITLE
TIDAL MUSIC VIDEOS DONT WORK

### ISSUE THREAD

**Issue by jaylex32** [nathom/streamrip#116]
Tidal music videos wont download, single videos or playlists, no videos wont download.
it just give me this error:

Traceback (most recent call last):
  File "/home/appbox/.local/bin/rip", line 8, in <module>
    sys.exit(main())
  File "/home/appbox/.local/lib/python3.8/site-packages/rip/cli.py", line 459, in main
    cli(obj={})
  File "/home/appbox/.local/lib/python3.8/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/home/appbox/.local/lib/python3.8/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/home/appbox/.local/lib/python3.8/site-packages/click/core.py", line 1646, in invoke
    super().invoke(ctx)
  File "/home/appbox/.local/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/appbox/.local/lib/python3.8/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/home/appbox/.local/lib/python3.8/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/appbox/.local/lib/python3.8/site-packages/rip/cli.py", line 121, in cli
    core.download()
  File "/home/appbox/.local/lib/python3.8/site-packages/rip/core.py", line 298, in download
    item.download(**arguments)
  File "/home/appbox/.local/lib/python3.8/site-packages/streamrip/media.py", line 737, in download
    self.path,
  File "/home/appbox/.local/lib/python3.8/site-packages/streamrip/media.py", line 778, in path
    os.makedirs(self.parent_folder, exist_ok=True)
  File "/usr/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)

**Comment by nathom** [comment]
I need more information than this. Please use the bug report template.
