### ISSUE TITLE
Tomlkit/Config Error

### ISSUE THREAD

**Issue by iamtheplauge** [nathom/streamrip#118]
Sorry to be a bother with another issue, but after I opened the config with Notepad, not a single function works except rip --help. I didn't change anything in the file, I simply opened it with Notepad.

Any other function I try, including checking the current version, results in this:

Traceback (most recent call last):
  File "c:\users\sam\appdata\local\programs\python\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\sam\appdata\local\programs\python\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Sam\AppData\Local\Programs\Python\Python39\Scripts\rip.exe\__main__.py", line 7, in <module>
  File "c:\users\sam\appdata\local\programs\python\python39\lib\site-packages\rip\cli.py", line 459, in main
    cli(obj={})
  File "c:\users\sam\appdata\local\programs\python\python39\lib\site-packages\click\core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\sam\appdata\local\programs\python\python39\lib\site-packages\click\core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "c:\users\sam\appdata\local\programs\python\python39\lib\site-packages\click\core.py", line 1646, in invoke
    super().invoke(ctx)
  File "c:\users\sam\appdata\local\programs\python\python39\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\sam\appdata\local\programs\python\python39\lib\site-packages\click\core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "c:\users\sam\appdata\local\programs\python\python39\lib\site-packages\click\decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "c:\users\sam\appdata\local\programs\python\python39\lib\site-packages\rip\cli.py", line 73, in cli
    config = Config()
  File "c:\users\sam\appdata\local\programs\python\python39\lib\site-packages\rip\config.py", line 56, in __init__
    self.load()
  File "c:\users\sam\appdata\local\programs\python\python39\lib\site-packages\rip\config.py", line 96, in load
    for k, v in tomlkit.loads(cfg.read().strip()).items():
  File "c:\users\sam\appdata\local\programs\python\python39\lib\site-packages\tomlkit\api.py", line 34, in loads
    return parse(string)
  File "c:\users\sam\appdata\local\programs\python\python39\lib\site-packages\tomlkit\api.py", line 51, in parse
    return Parser(string).parse()
  File "c:\users\sam\appdata\local\programs\python\python39\lib\site-packages\tomlkit\parser.py", line 160, in parse
    key, value = self._parse_table()
  File "c:\users\sam\appdata\local\programs\python\python39\lib\site-packages\tomlkit\parser.py", line 1154, in _parse_table
    item = self._parse_item()
  File "c:\users\sam\appdata\local\programs\python\python39\lib\site-packages\tomlkit\parser.py", line 306, in _parse_item
    return self._parse_key_value(True)
  File "c:\users\sam\appdata\local\programs\python\python39\lib\site-packages\tomlkit\parser.py", line 397, in _parse_key_value
    val = self._parse_value()
  File "c:\users\sam\appdata\local\programs\python\python39\lib\site-packages\tomlkit\parser.py", line 561, in _parse_value
    return self._parse_basic_string()
  File "c:\users\sam\appdata\local\programs\python\python39\lib\site-packages\tomlkit\parser.py", line 854, in _parse_basic_string
    return self._parse_string(StringType.SLB)
  File "c:\users\sam\appdata\local\programs\python\python39\lib\site-packages\tomlkit\parser.py", line 990, in _parse_string
    value += self._parse_escaped_char(delim.is_multiline())
  File "c:\users\sam\appdata\local\programs\python\python39\lib\site-packages\tomlkit\parser.py", line 897, in _parse_escaped_char
    raise self.parse_error(InvalidUnicodeValueError)
tomlkit.exceptions.InvalidUnicodeValueError: Invalid unicode value at line 3 col 13

I have no idea how to fix this. From my best guess, the tomlkit is no longer able to understand something in the config file, but I am not a code heavy person at all. I tried setting a different program to associate with the config like notepad++ but nothing changed. I tried uninstalling streamrip and reinstalling, and nothing. I even tried uninstalling/reinstalling pip and python and it still gives this error for any input other than --help.

This is all on the most recent version 0.7.0.

**Comment by nathom** [comment]
Please attach the config file with your credentials redacted.

**Comment by nathom** [comment]
Closing due to inactivity.
