### ISSUE TITLE
Bug: Qobuz downloading not working

### ISSUE THREAD

**Issue by kbruh** [nathom/streamrip#125]
## Bug Report

**Current Behavior**
Whenever I try to download from Deezer or Qobuz I get an error.

**Command used:**

```bash
rip -u
```

**Expected behavior**
The album should have downloaded.

**`streamrip` Configuration File (find using `rip config -o`):**

```toml
[downloads]
# Folder where tracks are downloaded to
folder = "/Volumes/KevinBackup/Kevins Stuff/Bruh/Music/Automatically Add to Music.localized"
# Put Qobuz albums in a 'Qobuz' folder, Tidal albums in 'Tidal' etc.
source_subdirectories = false
# Download (and convert) tracks all at once, instead of sequentially.
# If you are converting the tracks, or have fast internet, this will
# substantially improve processing speed.
concurrent = true


[qobuz]
# 1: 320kbps MP3, 2: 16/44.1, 3: 24/<=96, 4: 24/>=96
quality = 3
# This will download booklet pdfs that are included with some albums
download_booklets = true

email = ""
# This is an md5 hash of the plaintext password
password = ""
# Do not change
app_id = ""
# Do not change
secrets = []


[tidal]
# 0: 256kbps AAC, 1: 320kbps AAC, 2: 16/44.1 "HiFi" FLAC, 3: 24/44.1 "MQA" FLAC
quality = 3
# This will download videos included in Video Albums.
download_videos = true

# Do not change any of the fields below
user_id = ""
country_code = ""
access_token = ""
refresh_token = ""
# Tokens last 1 week after refresh. This is the Unix timestamp of the expiration
# time. If you haven't used streamrip in more than a week, you may have to log
# in again using `rip config --tidal`
token_expiry = ""

# Doesn't require login

[deezer]
# 0, 1, or 2
quality = 2


[soundcloud]
# Only 0 is available for now
quality = 0


[youtube]
# Only 0 is available for now
quality = 0
# Download the video along with the audio
download_videos = false
# The path to download the videos to
video_downloads_folder = "/Volumes/KevinBackup/Kevins Stuff/Bruh/Music/Automatically Add to Music.localized"

# This stores a list of item IDs so that repeats are not downloaded.

[database.downloads]
enabled = false
path = "/Users/kevinpulikkottil/Library/Application Support/streamrip/downloads.db"

# If a download fails, the item ID is stored here. Then, `rip repair` can be
# called to retry the downloads

[database.failed_downloads]
enabled = true
path = "/Users/kevinpulikkottil/Library/Application Support/streamrip/failed_downloads.db"

# Convert tracks to a codec after downloading them.

[conversion]
enabled = true
# FLAC, ALAC, OPUS, MP3, VORBIS, or AAC
codec = "ALAC"
# In Hz. Tracks are downsampled if their sampling rate is greater than this.
# Value of 48000 is recommended to maximize quality and minimize space
sampling_rate = 48000
# Only 16 and 24 are available. It is only applied when the bit depth is higher
# than this value.
bit_depth = 24

# Filter a Qobuz artist's discography. Set to 'true' to turn on a filter.

[filters]
# Remove Collectors Editions, live recordings, etc.
extras = false
# Picks the highest quality out of albums with identical titles.
repeats = false
# Remove EPs and Singles
non_albums = false
# Remove albums whose artist is not the one requested
features = false
# Skip non studio albums
non_studio_albums = false
# Only download remastered albums
non_remaster = false


[artwork]
# Write the image to the audio file
embed = true
# The size of the artwork to embed. Options: thumbnail, small, large, original.
# "original" images can be up to 30MB, and may fail embedding.
# Using "large" is recommended.
size = "large"
# Both of these options limit the size of the embedded artwork. If their values
# are larger than the actual dimensions of the image, they will be ignored.
max_width = 999999
max_height = 999999
# Save the cover image at the highest quality as a seperate jpg file
keep_hires_cover = false


[metadata]
# Sets the value of the 'ALBUM' field in the metadata to the playlist's name.
# This is useful if your music library software organizes tracks based on album name.
set_playlist_to_album = true
# Replaces the original track's tracknumber with it's position in the playlist
new_playlist_tracknumbers = true

# Changes the folder and file names generated by streamrip.

[filepaths]
# Create folders for single tracks within the downloads directory using the folder_format
# template
add_singles_to_folder = false
# Available keys: "albumartist", "title", "year", "bit_depth", "sampling_rate",
# "container", and "albumcomposer"
folder_format = "{albumartist} - {title} ({year}) [{container}] [{bit_depth}B-{sampling_rate}kHz]"
# Available keys: "tracknumber", "artist", "albumartist", "composer", "title",
# and "albumcomposer"
track_format = "{tracknumber}. {artist} - {title}"

# Last.fm playlists are downloaded by searching for the titles of the tracks

[lastfm]
# The source on which to search for the tracks.
source = "qobuz"
# If no results were found with the primary source, the item is searched for
# on this one.
fallback_source = "deezer"


[misc]
# Check whether a newer version of streamrip is available when starting up
check_for_updates = true

# Metadata to identify this config file. Do not change.
version = "0.7.1"
```

**Environment**

- `streamrip` version(s): 0.7.1
- Python version: 3.9
- OS: MacOS Big Sur 11.4

**Traceback**
```bash
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/bin/rip", line 8, in <module>
    sys.exit(main())
  File "/Users/kevinpulikkottil/Library/Python/3.9/lib/python/site-packages/rip/cli.py", line 477, in main
    cli(obj={})
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/click/core.py", line 1646, in invoke
    super().invoke(ctx)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/kevinpulikkottil/Library/Python/3.9/lib/python/site-packages/rip/cli.py", line 121, in cli
    core.download()
  File "/Users/kevinpulikkottil/Library/Python/3.9/lib/python/site-packages/rip/core.py", line 300, in download
    item.download(**arguments)
  File "/Users/kevinpulikkottil/Library/Python/3.9/lib/python/site-packages/streamrip/media.py", line 984, in download
    self._prepare_download(**kwargs)
  File "/Users/kevinpulikkottil/Library/Python/3.9/lib/python/site-packages/streamrip/media.py", line 1356, in _prepare_download
    downsize_image(
  File "/Users/kevinpulikkottil/Library/Python/3.9/lib/python/site-packages/streamrip/utils.py", line 394, in downsize_image
    from PIL import Image
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/PIL/Image.py", line 114, in <module>
    from . import _imaging as core
ImportError: dlopen(/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/PIL/_imaging.cpython-39-darwin.so, 2): no suitable image found.  Did find:
	/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/PIL/_imaging.cpython-39-darwin.so: mach-o, but wrong architecture
	/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/PIL/_imaging.cpython-39-darwin.so: mach-o, but wrong architecture
```

**Comment by nathom** [comment]
You have the x86 version of the Python Image Library (PIL). You need to install the universal binary or the arm64 version. Try following the instructions [here](https://github.com/python-pillow/Pillow/issues/5093#issuecomment-745283499).

**Comment by kbruh** [comment]
Ok thanks
