### ISSUE TITLE
Config Error

### ISSUE THREAD

**Issue by rbettendorf** [nathom/streamrip#14]
See https://github.com/nathom/streamrip/issues/12 for original issue.

After updating python to 3.9.1 as was suggested, now I am getting the following error when running a simple help command:

rip search -help
Traceback (most recent call last):
  File "/usr/local/bin/rip", line 5, in <module>
    from streamrip.cli import main
  File "/usr/local/lib/python3.9/site-packages/streamrip/cli.py", line 13, in <module>
    config = Config(CONFIG_PATH)
  File "/usr/local/lib/python3.9/site-packages/streamrip/config.py", line 90, in __init__
    self.dump(self.defaults)
  File "/usr/local/lib/python3.9/site-packages/streamrip/config.py", line 127, in dump
    with open(self._path, "w") as cfg:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/xxxx008/Library/Application Support/streamrip/config.yaml'

**Comment by TheProgramableTurtle** [comment]
Try `rip config --reset`

**Comment by rbettendorf** [comment]
That worked. Thanks so much!
