### ISSUE TITLE
[BUG] unexpected keywork accept_language

### ISSUE THREAD

**Issue by fsanna13** [nathom/streamrip#188]
### Describe the bug

No command is working, even just `rip` doesn't work. The message is always
`TypeError: __init__() got an unexpected keyword argument 'accept_language'`.

### Command Used

```bash
rip
```

### Debug Traceback

```text
Traceback (most recent call last):                                                                                        File "C:\Users\sanna\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main               return _run_code(code, main_globals, None,                                                                            File "C:\Users\sanna\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code                          exec(code, run_globals)                                                                                               File "C:\Users\sanna\AppData\Local\Programs\Python\Python39\Scripts\rip.exe\__main__.py", line 4, in <module>           File "C:\Users\sanna\AppData\Local\Programs\Python\Python39\lib\site-packages\rip\cli.py", line 17, in <module>           from .core import RipCore                                                                                             File "C:\Users\sanna\AppData\Local\Programs\Python\Python39\lib\site-packages\rip\core.py", line 89, in <module>          class RipCore(list):                                                                                                  File "C:\Users\sanna\AppData\Local\Programs\Python\Python39\lib\site-packages\rip\core.py", line 95, in RipCore           "deezer": DeezerClient(),                                                                                             File "C:\Users\sanna\AppData\Local\Programs\Python\Python39\lib\site-packages\streamrip\clients.py", line 482, in __init__                                                                                                                        self.client = deezer.Deezer(accept_language="en-US,en;q=0.5")                                                       TypeError: __init__() got an unexpected keyword argument 'accept_language'
```

### Config File

```toml
Same error appears, can't open the configuration file.
```

### Operating System

Windows

### streamrip version

Can't get the verison (same error appears)

**Comment by nathom** [comment]
I need the full traceback. Try running `rip config -o -vvv` and pasting the output here.

**Comment by rlabrach** [comment]
hello
i have the same problem. I'm running PopOS Linux

rip config -o -vvv
Traceback (most recent call last):
  File "/usr/local/bin/rip", line 5, in <module>
    from rip.cli import main
  File "/usr/local/lib/python3.9/dist-packages/rip/cli.py", line 17, in <module>
    from .core import RipCore
  File "/usr/local/lib/python3.9/dist-packages/rip/core.py", line 89, in <module>
    class RipCore(list):
  File "/usr/local/lib/python3.9/dist-packages/rip/core.py", line 95, in RipCore
    "deezer": DeezerClient(),
  File "/usr/local/lib/python3.9/dist-packages/streamrip/clients.py", line 482, in __init__
    self.client = deezer.Deezer(accept_language="en-US,en;q=0.5")
TypeError: __init__() got an unexpected keyword argument 'accept_language'

**Comment by nathom** [comment]
It looks like you downloaded a newer version of `deezer-py`. Try running

```
pip3 install deezer-py==1.2.2
```

and running again. This issue will be fixed in the next update.

**Comment by Pozinux** [comment]
Thanks, it resolved the issue for me. :)

**Comment by rlabrach** [comment]
Hello
that's ok for me too !!
THANKS

**Comment by otivo** [comment]
> It looks like you downloaded a newer version of `deezer-py`. Try running
> 
> ```
> pip3 install deezer-py==1.2.2
> ```
> 
> and running again. This issue will be fixed in the next update.

I experienced the same problem. After attempting to resolve using this, it now gives the following


The command "https://www.deezer.com/en/album/223234712" does not exist.

If this was unexpected, please open a Bug Report at https://github.com/nathom/streamrip/issues/new/choose

**Comment by otivo** [comment]
> It looks like you downloaded a newer version of `deezer-py`. Try running
> 
> ```
> pip3 install deezer-py==1.2.2
> ```
> 
> and running again. This issue will be fixed in the next update.

This has worked for me. Thanks!!

**Comment by CyberLykan** [comment]
That works. Thanks!
