### ISSUE TITLE
[BUG] <title> RIP doesn't start correectly

### ISSUE THREAD

**Issue by androsco** [nathom/streamrip#220]
### Describe the bug

When I type "rip" in the powershell I receive an error. 
See below.

### Command Used

```bash
rip
```

### Debug Traceback

```text
Traceback (most recent call last):
  File "C:\Users\bardu\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\bardu\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\bardu\AppData\Local\Programs\Python\Python310\Scripts\rip.exe\__main__.py", line 4, in <module>
  File "C:\Users\bardu\AppData\Local\Programs\Python\Python310\lib\site-packages\rip\cli.py", line 15, in <module>
    from .core import RipCore
  File "C:\Users\bardu\AppData\Local\Programs\Python\Python310\lib\site-packages\rip\core.py", line 87, in <module>
    class RipCore(list):
  File "C:\Users\bardu\AppData\Local\Programs\Python\Python310\lib\site-packages\rip\core.py", line 93, in RipCore
    "deezer": DeezerClient(),
  File "C:\Users\bardu\AppData\Local\Programs\Python\Python310\lib\site-packages\streamrip\clients.py", line 448, in __init__
    self.client = deezer.Deezer(accept_language="en-US,en;q=0.5")
TypeError: Deezer.__init__() got an unexpected keyword argument 'accept_language'
```

### Config File

```toml
Traceback (most recent call last):
  File "C:\Users\bardu\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\bardu\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\bardu\AppData\Local\Programs\Python\Python310\Scripts\rip.exe\__main__.py", line 4, in <module>
  File "C:\Users\bardu\AppData\Local\Programs\Python\Python310\lib\site-packages\rip\cli.py", line 15, in <module>
    from .core import RipCore
  File "C:\Users\bardu\AppData\Local\Programs\Python\Python310\lib\site-packages\rip\core.py", line 87, in <module>
    class RipCore(list):
  File "C:\Users\bardu\AppData\Local\Programs\Python\Python310\lib\site-packages\rip\core.py", line 93, in RipCore
    "deezer": DeezerClient(),
  File "C:\Users\bardu\AppData\Local\Programs\Python\Python310\lib\site-packages\streamrip\clients.py", line 448, in __init__
    self.client = deezer.Deezer(accept_language="en-US,en;q=0.5")
TypeError: Deezer.__init__() got an unexpected keyword argument 'accept_language'
```

### Operating System

Wondows 10

### streamrip version

Traceback (most recent call last):   File "C:\Users\bardu\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main     return _run_code(code, main_globals, None,   File "C:\Users\bardu\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code     exec(code, run_globals)   File "C:\Users\bardu\AppData\Local\Programs\Python\Python310\Scripts\rip.exe\__main__.py", line 4, in <module>   File "C:\Users\bardu\AppData\Local\Programs\Python\Python310\lib\site-packages\rip\cli.py", line 15, in <module>     from .core import RipCore   File "C:\Users\bardu\AppData\Local\Programs\Python\Python310\lib\site-packages\rip\core.py", line 87, in <module>     class RipCore(list):   File "C:\Users\bardu\AppData\Local\Programs\Python\Python310\lib\site-packages\rip\core.py", line 93, in RipCore     "deezer": DeezerClient(),   File "C:\Users\bardu\AppData\Local\Programs\Python\Python310\lib\site-packages\streamrip\clients.py", line 448, in __init__     self.client = deezer.Deezer(accept_language="en-US,en;q=0.5") TypeError: Deezer.__init__() got an unexpected keyword argument 'accept_language'

### Additional context

python --version 
Python 3.10.0

pip --version
pip 21.3.1 from C:\Users\bardu\AppData\Local\Programs\Python\Python310\lib\site-packages\pip (python 3.10)

**Comment by simsar26** [comment]
I have that same problem.

**Comment by nathom** [comment]
You need to update streamrip.


```
pip3 install streamrip --upgrade
```

**Comment by androsco** [comment]
Solved, install a previous version of Python. V3.9. But Tidal download supports up to 48 khz not MQA. Bye. Andrea Il 1 nov 2021 22:08, simsar26 ***@***.***> ha scritto:
I have that same problem.

**Comment by simsar26** [comment]
> Solved, install a previous version of Python. V3.9. But Tidal download supports up to 48 khz not MQA. Bye. Andrea Il 1 nov 2021 22:08, simsar26 ***@***.***> ha scritto: I have that same problem. —You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.

Thank you.
