### ISSUE TITLE
[BUG] Can't get the main menu to even show

### ISSUE THREAD

**Issue by MrBonesHOK** [nathom/streamrip#234]
### Describe the bug

I just installed Python 3.10 to E:\Users\xxxx\AppData\Local\Programs\Python\Python310 & streamrip inside the dir, E:\Users\xxxx\AppData\Local\Programs\Python\Python310\streamrip-main. I installed via CMD, using pip3 install streamrip --upgrade & it appears to install correctly. So now when I have CMD up & I'm in the Python310 dir & type rip, nothing comes up but this error (I cannot for the life of me figure out what I'm doing wrong):

  File "E:\Users\xxxx\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "E:\Users\xxxx\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "E:\Users\xxxx\AppData\Local\Programs\Python\Python310\Scripts\rip.exe\__main__.py", line 4, in <module>
  File "E:\Users\xxxx\AppData\Local\Programs\Python\Python310\lib\site-packages\rip\cli.py", line 15, in <module>
    from .core import RipCore
  File "E:\Users\xxxx\AppData\Local\Programs\Python\Python310\lib\site-packages\rip\core.py", line 87, in <module>
    class RipCore(list):
  File "E:\Users\xxxx\AppData\Local\Programs\Python\Python310\lib\site-packages\rip\core.py", line 93, in RipCore
    "deezer": DeezerClient(),
  File "E:\Users\xxxx\AppData\Local\Programs\Python\Python310\lib\site-packages\streamrip\clients.py", line 448, in __init__
    self.client = deezer.Deezer(accept_language="en-US,en;q=0.5")
TypeError: Deezer.__init__() got an unexpected keyword argument 'accept_language'

### Command Used

```bash
rip
```

### Debug Traceback

```text
Traceback (most recent call last):
  File "E:\Users\xxxx\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "E:\Users\xxxx\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "E:\Users\xxxx\AppData\Local\Programs\Python\Python310\Scripts\rip.exe\__main__.py", line 4, in <module>
  File "E:\Users\xxxx\AppData\Local\Programs\Python\Python310\lib\site-packages\rip\cli.py", line 15, in <module>
    from .core import RipCore
  File "E:\Users\xxxx\AppData\Local\Programs\Python\Python310\lib\site-packages\rip\core.py", line 87, in <module>
    class RipCore(list):
  File "E:\Users\xxxx\AppData\Local\Programs\Python\Python310\lib\site-packages\rip\core.py", line 93, in RipCore
    "deezer": DeezerClient(),
  File "E:\Users\xxxx\AppData\Local\Programs\Python\Python310\lib\site-packages\streamrip\clients.py", line 448, in __init__
    self.client = deezer.Deezer(accept_language="en-US,en;q=0.5")
TypeError: Deezer.__init__() got an unexpected keyword argument 'accept_language'
```

### Config File

```toml
doesnt work, same error as above
```

### Operating System

Win10

### streamrip version

doesnt work, same error as above

**Comment by MrBonesHOK** [comment]
It's b/c it's Python 3.10....need to use 3.9
