### ISSUE TITLE
[BUG] Unable to rip 24/44 from Tidal

### ISSUE THREAD

**Issue by TofuOrganic** [nathom/streamrip#287]
### Describe the bug

I have Tidal HiFi Plus subscription.

When trying to rip an album/track of Master Quality the downloaded file is only 16Bit.

Triple checked my config file and attempted to set max quality for the URL download also with no success.

### Command Used

```bash
rip url https://tidal.com/browse/album/11343622
```

### Debug Traceback

```text
C:\Users\Cloud>rip url https://tidal.com/browse/track/211598015 -vvv
DEBUG:streamrip:Config loaded
DEBUG:streamrip:Parsed urls: [('tidal', 'track', '211598015')]
DEBUG:streamrip:Searching for {'id': '211598015'} in database
DEBUG:streamrip:Executing SELECT EXISTS(SELECT 1 FROM downloads WHERE id=?)
DEBUG:streamrip:{'quality': 3, 'download_videos': True, 'user_id': 184820038, 'country_code': 'NZ', 'access_token': 'hidden', 'refresh_token': 'hidden', 'token_expiry': hidden}
DEBUG:streamrip:Logging in with access token
Logged into Tidal
DEBUG:streamrip:Config saved: C:\Users\Cloud\AppData\Local\streamrip\streamrip\config.toml
DEBUG:streamrip:{'id': 'hidden'}
DEBUG:streamrip:{'downloads': {'folder': 'D:\\Downloaded\\StreamRip', 'source_subdirectories': False, 'concurrency': {'enabled': True, 'max_connections': 3}}, 'qobuz': {'quality': 3, 'download_booklets': True, 'email': '', 'password': '', 'app_id': '', 'secrets': []}, 'tidal': {'quality': 3, 'download_videos': True, 'user_id': hidden, 'country_code': 'NZ', 'access_token': 'hidden', 'refresh_token': 'hidden', 'token_expiry': hidden}, 'deezer': {'quality': 2, 'arl': '', 'use_deezloader': True, 'deezloader_warnings': True}, 'soundcloud': {'quality': 0, 'client_id': '', 'app_version': ''}, 'youtube': {'quality': 0, 'download_videos': False, 'video_downloads_folder': ''}, 'database': {'downloads': {'enabled': True, 'path': 'C:\\Users\\Cloud\\AppData\\Local\\streamrip\\streamrip\\downloads.db'}, 'failed_downloads': {'enabled': True, 'path': 'C:\\Users\\Cloud\\AppData\\Local\\streamrip\\streamrip\\failed_downloads.db'}}, 'conversion': {'enabled': False, 'codec': 'ALAC', 'sampling_rate': 48000, 'bit_depth': 24, 'lossy_bitrate': 320}, 'filters': {'extras': False, 'repeats': False, 'non_albums': False, 'features': False, 'non_studio_albums': False, 'non_remaster': False}, 'artwork': {'embed': True, 'size': 'large', 'max_width': -1, 'max_height': -1, 'keep_hires_cover': True}, 'metadata': {'set_playlist_to_album': True, 'new_playlist_tracknumbers': True, 'exclude': ['comment', 'description', 'purchase_date', 'grouping', 'lyrics']}, 'filepaths': {'add_singles_to_folder': False, 'folder_format': '{albumartist}\\{title} ({year}) [{container}] [{bit_depth}B-{sampling_rate}kHz]', 'track_format': '{tracknumber} - {title}', 'restrict_characters': False}, 'lastfm': {'source': 'qobuz', 'fallback_source': 'deezer'}, 'theme': {'progress_bar': 'dainty'}, 'misc': {'version': '1.9.2'}}
DEBUG:streamrip:Arguments from config: {'restrict_filenames': False, 'parent_folder': 'D:\\Downloaded\\StreamRip', 'folder_format': '{albumartist}\\{title} ({year}) [{container}] [{bit_depth}B-{sampling_rate}kHz]', 'track_format': '{tracknumber} - {title}', 'embed_cover': True, 'embed_cover_size': 'large', 'keep_hires_cover': True, 'set_playlist_to_album': True, 'stay_temp': False, 'conversion': {'enabled': False, 'codec': 'ALAC', 'sampling_rate': 48000, 'bit_depth': 24, 'lossy_bitrate': 320}, 'concurrent_downloads': True, 'max_connections': 3, 'new_tracknumbers': True, 'download_videos': True, 'download_booklets': True, 'download_youtube_videos': False, 'youtube_video_downloads_folder': '', 'add_singles_to_folder': False, 'max_artwork_width': -1, 'max_artwork_height': -1, 'exclude_tags': ['comment', 'description', 'purchase_date', 'grouping', 'lyrics']}
DEBUG:streamrip:Loading metadata
--- Logging error ---
Traceback (most recent call last):
  File "C:\Users\Cloud\AppData\Local\Programs\Python\Python310\lib\logging\__init__.py", line 1103, in emit
    stream.write(msg + self.terminator)
  File "C:\Users\Cloud\AppData\Local\Programs\Python\Python310\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u2117' in position 329: character maps to <undefined>
Call stack:
  File "C:\Users\Cloud\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Cloud\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\Cloud\AppData\Local\Programs\Python\Python310\Scripts\rip.exe\__main__.py", line 7, in <module>
    sys.exit(main())
  File "C:\Users\Cloud\AppData\Local\Programs\Python\Python310\lib\site-packages\rip\cli.py", line 829, in main
    application.run()
  File "C:\Users\Cloud\AppData\Local\Programs\Python\Python310\lib\site-packages\cleo\application.py", line 330, in run
    exit_code = self._run(io)
  File "C:\Users\Cloud\AppData\Local\Programs\Python\Python310\lib\site-packages\rip\cli.py", line 759, in _run
    super()._run(io)
  File "C:\Users\Cloud\AppData\Local\Programs\Python\Python310\lib\site-packages\cleo\application.py", line 425, in _run    exit_code = self._run_command(command, io)
  File "C:\Users\Cloud\AppData\Local\Programs\Python\Python310\lib\site-packages\cleo\application.py", line 432, in _run_command
    return command.run(io)
  File "C:\Users\Cloud\AppData\Local\Programs\Python\Python310\lib\site-packages\cleo\commands\base_command.py", line 118, in run
    status_code = self.execute(io)
  File "C:\Users\Cloud\AppData\Local\Programs\Python\Python310\lib\site-packages\cleo\commands\command.py", line 85, in execute
    return self.handle()
  File "C:\Users\Cloud\AppData\Local\Programs\Python\Python310\lib\site-packages\rip\cli.py", line 124, in handle
    core.download()
  File "C:\Users\Cloud\AppData\Local\Programs\Python\Python310\lib\site-packages\rip\core.py", line 306, in download
    item.load_meta(**arguments)
  File "C:\Users\Cloud\AppData\Local\Programs\Python\Python310\lib\site-packages\streamrip\media.py", line 210, in load_meta
    self.resp = self.client.get(self.id, media_type="track")
  File "C:\Users\Cloud\AppData\Local\Programs\Python\Python310\lib\site-packages\streamrip\clients.py", line 772, in get    resp = self._api_get(item_id, media_type)
  File "C:\Users\Cloud\AppData\Local\Programs\Python\Python310\lib\site-packages\streamrip\clients.py", line 1030, in _api_get
    logger.debug(item)
Message: {'id': 211598015, 'title': 'Cold Winter (feat. Mad Clown)', 'duration': 219, 'replayGain': -10.74, 'peak': 0.997345, 'allowStreaming': True, 'streamReady': True, 'streamStartDate': '2022-01-18T22:00:00.000+0000', 'premiumStreamingOnly': False, 'trackNumber': 3, 'volumeNumber': 1, 'version': None, 'popularity': 4, 'copyright': '℗ 2022 KONNECT ENTERTAINMENT', 'url': 'http://www.tidal.com/track/211598015', 'isrc': 'KRA252200028', 'editable': False, 'explicit': False, 'audioQuality': 'HI_RES', 'audioModes': ['STEREO'], 'artist': {'id': 10196098, 'name': 'YUJU', 'type': 'MAIN', 'picture': None}, 'artists': [{'id': 10196098, 'name': 'YUJU', 'type': 'MAIN', 'picture': None}, {'id': 4414539, 'name': 'Mad Clown', 'type': 'FEATURED', 'picture': None}], 'album': {'id': 211598012, 'title': '[REC.]', 'cover': 'ce16f758-4053-4426-bfff-c35221914f98', 'vibrantColor': '#e2695a', 'videoCover': None}, 'mixes': {}}
Arguments: ()
DEBUG:streamrip:{'id': 211598015, 'title': 'Cold Winter (feat. Mad Clown)', 'duration': 219, 'replayGain': -10.74, 'peak': 0.997345, 'allowStreaming': True, 'streamReady': True, 'streamStartDate': '2022-01-18T22:00:00.000+0000', 'premiumStreamingOnly': False, 'trackNumber': 3, 'volumeNumber': 1, 'version': None, 'popularity': 4, 'copyright': '℗ 2022 KONNECT ENTERTAINMENT', 'url': 'http://www.tidal.com/track/211598015', 'isrc': 'KRA252200028', 'editable': False, 'explicit': False, 'audioQuality': 'HI_RES', 'audioModes': ['STEREO'], 'artist': {'id': 10196098, 'name': 'YUJU', 'type': 'MAIN', 'picture': None}, 'artists': [{'id': 10196098, 'name': 'YUJU', 'type': 'MAIN', 'picture': None}, {'id': 4414539, 'name': 'Mad Clown', 'type': 'FEATURED', 'picture': None}], 'album': {'id': 211598012, 'title': '[REC.]', 'cover': 'ce16f758-4053-4426-bfff-c35221914f98', 'vibrantColor': '#e2695a', 'videoCover': None}, 'mixes': {}}
--- Logging error ---
Traceback (most recent call last):
  File "C:\Users\Cloud\AppData\Local\Programs\Python\Python310\lib\logging\__init__.py", line 1103, in emit
    stream.write(msg + self.terminator)
  File "C:\Users\Cloud\AppData\Local\Programs\Python\Python310\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u2117' in position 329: character maps to <undefined>
Call stack:
  File "C:\Users\Cloud\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Cloud\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\Cloud\AppData\Local\Programs\Python\Python310\Scripts\rip.exe\__main__.py", line 7, in <module>
    sys.exit(main())
  File "C:\Users\Cloud\AppData\Local\Programs\Python\Python310\lib\site-packages\rip\cli.py", line 829, in main
    application.run()
  File "C:\Users\Cloud\AppData\Local\Programs\Python\Python310\lib\site-packages\cleo\application.py", line 330, in run
    exit_code = self._run(io)
  File "C:\Users\Cloud\AppData\Local\Programs\Python\Python310\lib\site-packages\rip\cli.py", line 759, in _run
    super()._run(io)
  File "C:\Users\Cloud\AppData\Local\Programs\Python\Python310\lib\site-packages\cleo\application.py", line 425, in _run    exit_code = self._run_command(command, io)
  File "C:\Users\Cloud\AppData\Local\Programs\Python\Python310\lib\site-packages\cleo\application.py", line 432, in _run_command
    return command.run(io)
  File "C:\Users\Cloud\AppData\Local\Programs\Python\Python310\lib\site-packages\cleo\commands\base_command.py", line 118, in run
    status_code = self.execute(io)
  File "C:\Users\Cloud\AppData\Local\Programs\Python\Python310\lib\site-packages\cleo\commands\command.py", line 85, in execute
    return self.handle()
  File "C:\Users\Cloud\AppData\Local\Programs\Python\Python310\lib\site-packages\rip\cli.py", line 124, in handle
    core.download()
  File "C:\Users\Cloud\AppData\Local\Programs\Python\Python310\lib\site-packages\rip\core.py", line 306, in download
    item.load_meta(**arguments)
  File "C:\Users\Cloud\AppData\Local\Programs\Python\Python310\lib\site-packages\streamrip\media.py", line 210, in load_meta
    self.resp = self.client.get(self.id, media_type="track")
  File "C:\Users\Cloud\AppData\Local\Programs\Python\Python310\lib\site-packages\streamrip\clients.py", line 773, in get    logger.debug(resp)
Message: {'id': 211598015, 'title': 'Cold Winter (feat. Mad Clown)', 'duration': 219, 'replayGain': -10.74, 'peak': 0.997345, 'allowStreaming': True, 'streamReady': True, 'streamStartDate': '2022-01-18T22:00:00.000+0000', 'premiumStreamingOnly': False, 'trackNumber': 3, 'volumeNumber': 1, 'version': None, 'popularity': 4, 'copyright': '℗ 2022 KONNECT ENTERTAINMENT', 'url': 'http://www.tidal.com/track/211598015', 'isrc': 'KRA252200028', 'editable': False, 'explicit': False, 'audioQuality': 'HI_RES', 'audioModes': ['STEREO'], 'artist': {'id': 10196098, 'name': 'YUJU', 'type': 'MAIN', 'picture': None}, 'artists': [{'id': 10196098, 'name': 'YUJU', 'type': 'MAIN', 'picture': None}, {'id': 4414539, 'name': 'Mad Clown', 'type': 'FEATURED', 'picture': None}], 'album': {'id': 211598012, 'title': '[REC.]', 'cover': 'ce16f758-4053-4426-bfff-c35221914f98', 'vibrantColor': '#e2695a', 'videoCover': None}, 'mixes': {}}
Arguments: ()
DEBUG:streamrip:{'id': 211598015, 'title': 'Cold Winter (feat. Mad Clown)', 'duration': 219, 'replayGain': -10.74, 'peak': 0.997345, 'allowStreaming': True, 'streamReady': True, 'streamStartDate': '2022-01-18T22:00:00.000+0000', 'premiumStreamingOnly': False, 'trackNumber': 3, 'volumeNumber': 1, 'version': None, 'popularity': 4, 'copyright': '℗ 2022 KONNECT ENTERTAINMENT', 'url': 'http://www.tidal.com/track/211598015', 'isrc': 'KRA252200028', 'editable': False, 'explicit': False, 'audioQuality': 'HI_RES', 'audioModes': ['STEREO'], 'artist': {'id': 10196098, 'name': 'YUJU', 'type': 'MAIN', 'picture': None}, 'artists': [{'id': 10196098, 'name': 'YUJU', 'type': 'MAIN', 'picture': None}, {'id': 4414539, 'name': 'Mad Clown', 'type': 'FEATURED', 'picture': None}], 'album': {'id': 211598012, 'title': '[REC.]', 'cover': 'ce16f758-4053-4426-bfff-c35221914f98', 'vibrantColor': '#e2695a', 'videoCover': None}, 'mixes': {}}
Downloading YUJU - Cold Winter (feat. Mad Clown)

DEBUG:streamrip:Track meta formatter {'tracknumber': 3, 'artist': 'YUJU', 'albumartist': None, 'composer': None, 'title': 'Cold Winter (feat. Mad Clown)', 'albumcomposer': None, 'explicit': False}
DEBUG:streamrip:Formatter keys: {tracknumber} - {title}
DEBUG:streamrip:'tracknumber'
DEBUG:streamrip:3
DEBUG:streamrip:2
DEBUG:streamrip:'title'
DEBUG:streamrip:Cold Winter (feat. Mad Clown)
DEBUG:streamrip:1
DEBUG:streamrip:Formatted path: D:\Downloaded\StreamRip\03 - Cold Winter (feat. Mad Clown).flac
DEBUG:streamrip:Downloading cover from https://resources.tidal.com/images/ce16f758/4053/4426/bfff/c35221914f98/640x640.jpg
Cover |███████████████████████████████████████████████████████████████████████████████████████| 00:00 left at 4.76MB/s
DEBUG:streamrip:{'mimeType': 'audio/flac', 'codecs': 'mqa', 'encryptionType': 'NONE', 'urls': ['http://sp-pr-cf.audio.tidal.com/mediatracks/CAEaKRInZmQ5N2EzYjg2MDdkY2UzM2M0ZjIzYzNiNmI5OWNhZWFfNjAubXA0/0.flac?Expires=1643003170&Signature=DWBwZaUEsN6MQyWmQVAnE95yhZ84Q~6UB9wC5wM2ol4pof~JVODZpousgh3lSSs2mmALvcRKQQpVzrvHMnNpt052WDc~hNDdJv~DGozeD-sAtXWreWrA3rGmw8WlLVVsgJR~EDzi7inmROR24dKecZGq9f7b2b2CIbarLMTYqa1jf9Q0AtUsM9IJaSpkZdAYr~FtDIQzXh2r4p0lnqp3gziXH~K9IOKm8ymkSmVJLorZuejP3~iPsx3EKfI~fUp89romSS5UuutRlTlwRb2YXAaIRGRGRnjmiM78WqjKsRpk70bDewy96ez9nby5sWE3O2cgdqiB5R-KnYZvWPZbnQ__&Key-Pair-Id=APKAIZ3WPBE4R6SP555A']}
DEBUG:streamrip:Downloadable URL found: http://sp-pr-cf.audio.tidal.com/mediatracks/CAEaKRInZmQ5N2EzYjg2MDdkY2UzM2M0ZjIzYzNiNmI5OWNhZWFfNjAubXA0/0.flac?Expires=1643003170&Signature=DWBwZaUEsN6MQyWmQVAnE95yhZ84Q~6UB9wC5wM2ol4pof~JVODZpousgh3lSSs2mmALvcRKQQpVzrvHMnNpt052WDc~hNDdJv~DGozeD-sAtXWreWrA3rGmw8WlLVVsgJR~EDzi7inmROR24dKecZGq9f7b2b2CIbarLMTYqa1jf9Q0AtUsM9IJaSpkZdAYr~FtDIQzXh2r4p0lnqp3gziXH~K9IOKm8ymkSmVJLorZuejP3~iPsx3EKfI~fUp89romSS5UuutRlTlwRb2YXAaIRGRGRnjmiM78WqjKsRpk70bDewy96ez9nby5sWE3O2cgdqiB5R-KnYZvWPZbnQ__&Key-Pair-Id=APKAIZ3WPBE4R6SP555A
Track 03 |████████████████████████████████████████████████████████████████████████████████████| 00:00 left at 46.0MB/s
DEBUG:streamrip:Downloaded: D:\Downloaded\StreamRip\03 - Cold Winter (feat. Mad Clown).flac -> D:\Downloaded\StreamRip\03 - Cold Winter (feat. Mad Clown).flac
DEBUG:streamrip:Executing INSERT INTO downloads (id) VALUES (?)
DEBUG:streamrip:Items to add: ('211598015',)
DEBUG:streamrip:Tagging file with FLAC container
DEBUG:streamrip:Excluded tags: {'lyrics', 'description', 'purchase_date', 'grouping', 'comment'}
DEBUG:streamrip:attr: title
DEBUG:streamrip:Adding tag TITLE: Cold Winter (feat. Mad Clown)
DEBUG:streamrip:Setting TITLE tag to Cold Winter (feat. Mad Clown)
DEBUG:streamrip:attr: artist
DEBUG:streamrip:Adding tag ARTIST: YUJU
DEBUG:streamrip:Setting ARTIST tag to YUJU
DEBUG:streamrip:attr: album
DEBUG:streamrip:Adding tag ALBUM: [REC.]
DEBUG:streamrip:Setting ALBUM tag to [REC.]
DEBUG:streamrip:attr: albumartist
DEBUG:streamrip:attr: composer
DEBUG:streamrip:attr: year
DEBUG:streamrip:attr: comment
DEBUG:streamrip:attr: description
DEBUG:streamrip:attr: purchase_date
DEBUG:streamrip:attr: grouping
DEBUG:streamrip:attr: genre
DEBUG:streamrip:attr: lyrics
DEBUG:streamrip:attr: encoder
DEBUG:streamrip:attr: copyright
DEBUG:streamrip:attr: compilation
DEBUG:streamrip:attr: cover
DEBUG:streamrip:attr: tracknumber
DEBUG:streamrip:Adding tag TRACKNUMBER: 03
DEBUG:streamrip:Setting TRACKNUMBER tag to 03
DEBUG:streamrip:attr: discnumber
DEBUG:streamrip:Adding tag DISCNUMBER: 01
DEBUG:streamrip:Setting DISCNUMBER tag to 01
DEBUG:streamrip:attr: tracktotal
DEBUG:streamrip:Adding tag TRACKTOTAL: 01
DEBUG:streamrip:Setting TRACKTOTAL tag to 01
DEBUG:streamrip:attr: disctotal
DEBUG:streamrip:Adding tag DISCTOTAL: 01
DEBUG:streamrip:Setting DISCTOTAL tag to 01
DEBUG:streamrip:attr: date
```

### Config File

```toml
[downloads]
# Folder where tracks are downloaded to
folder = "D:\\Downloaded\\StreamRip"
# Put Qobuz albums in a 'Qobuz' folder, Tidal albums in 'Tidal' etc.
source_subdirectories = false

[downloads.concurrency]
# Download (and convert) tracks all at once, instead of sequentially. 
# If you are converting the tracks, or have fast internet, this will 
# substantially improve processing speed.
enabled = true
# The maximum number of tracks to download at once
# If you have very fast internet, you will benefit from a higher value,
# A value that is too high for your bandwidth may cause slowdowns
max_connections = 3

[qobuz]
# 1: 320kbps MP3, 2: 16/44.1, 3: 24/<=96, 4: 24/>=96
quality = 3
# This will download booklet pdfs that are included with some albums
download_booklets = true

email = ""
# This is an md5 hash of the plaintext password
password = ""
# Do not change
app_id = ""
# Do not change
secrets = []

[tidal]
# 0: 256kbps AAC, 1: 320kbps AAC, 2: 16/44.1 "HiFi" FLAC, 3: 24/44.1 "MQA" FLAC
quality = 3
# This will download videos included in Video Albums.
download_videos = true

# Do not change any of the fields below
user_id = hidden
country_code = "NZ"
access_token = "hidden"
refresh_token = "hidden"
# Tokens last 1 week after refresh. This is the Unix timestamp of the expiration
# time. If you haven't used streamrip in more than a week, you may have to log
# in again using `rip config --tidal`
token_expiry = 1643603081.297828

[deezer]
# 0, 1, or 2
# This only applies to paid Deezer subscriptions. Those using deezloader
# are automatically limited to quality = 1
quality = 2
# An authentication cookie that allows streamrip to use your Deezer account
# See https://github.com/nathom/streamrip/wiki/Finding-Your-Deezer-ARL-Cookie
# for instructions on how to find this
arl = ""
# This allows for free 320kbps MP3 downloads from Deezer
# If an arl is provided, deezloader is never used
use_deezloader = true
# This warns you when the paid deezer account is not logged in and rip falls
# back to deezloader, which is unreliable
deezloader_warnings = true

[soundcloud]
# Only 0 is available for now
quality = 0
# This changes periodically, so it needs to be updated
client_id = ""
app_version = ""

[youtube]
# Only 0 is available for now
quality = 0
# Download the video along with the audio
download_videos = false
# The path to download the videos to
video_downloads_folder = ""

# This stores a list of item IDs so that repeats are not downloaded.

[database.downloads]
enabled = true
path = "C:\\Users\\Cloud\\AppData\\Local\\streamrip\\streamrip\\downloads.db"

# If a download fails, the item ID is stored here. Then, `rip repair` can be
# called to retry the downloads

[database.failed_downloads]
enabled = true
path = "C:\\Users\\Cloud\\AppData\\Local\\streamrip\\streamrip\\failed_downloads.db"

# Convert tracks to a codec after downloading them.

[conversion]
enabled = false
# FLAC, ALAC, OPUS, MP3, VORBIS, or AAC
codec = "ALAC"
# In Hz. Tracks are downsampled if their sampling rate is greater than this. 
# Value of 48000 is recommended to maximize quality and minimize space
sampling_rate = 48000
# Only 16 and 24 are available. It is only applied when the bit depth is higher
# than this value.
bit_depth = 24
# Only applicable for lossy codecs
lossy_bitrate = 320

# Filter a Qobuz artist's discography. Set to 'true' to turn on a filter.

[filters]
# Remove Collectors Editions, live recordings, etc.
extras = false
# Picks the highest quality out of albums with identical titles.
repeats = false
# Remove EPs and Singles
non_albums = false
# Remove albums whose artist is not the one requested
features = false
# Skip non studio albums
non_studio_albums = false
# Only download remastered albums
non_remaster = false

[artwork]
# Write the image to the audio file
embed = true
# The size of the artwork to embed. Options: thumbnail, small, large, original.
# "original" images can be up to 30MB, and may fail embedding. 
# Using "large" is recommended.
size = "large"
# Both of these options limit the size of the embedded artwork. If their values
# are larger than the actual dimensions of the image, they will be ignored.
# If either value is -1, the image is left untouched.
max_width = -1
max_height = -1
# Save the cover image at the highest quality as a seperate jpg file
keep_hires_cover = true

[metadata]
# Sets the value of the 'ALBUM' field in the metadata to the playlist's name. 
# This is useful if your music library software organizes tracks based on album name.
set_playlist_to_album = true
# Replaces the original track's tracknumber with it's position in the playlist
new_playlist_tracknumbers = true
# The following metadata tags won't be applied
# See https://github.com/nathom/streamrip/wiki/Metadata-Tag-Names for more info
exclude = ["comment", "description", "purchase_date", "grouping", "lyrics"]

# Changes the folder and file names generated by streamrip.

[filepaths]
# Create folders for single tracks within the downloads directory using the folder_format
# template
add_singles_to_folder = false
# Available keys: "albumartist", "title", "year", "bit_depth", "sampling_rate",
# "container", "id", and "albumcomposer"
folder_format = "{albumartist}\\{title} ({year}) [{container}] [{bit_depth}B-{sampling_rate}kHz]"
# Available keys: "tracknumber", "artist", "albumartist", "composer", "title",
# and "albumcomposer"
track_format = "{tracknumber} - {title}"
# Only allow printable ASCII characters in filenames.
restrict_characters = false

# Last.fm playlists are downloaded by searching for the titles of the tracks

[lastfm]
# The source on which to search for the tracks.
source = "qobuz"
# If no results were found with the primary source, the item is searched for 
# on this one.
fallback_source = "deezer"

[theme]
# Options: "dainty" or "plain"
progress_bar = "dainty"

[misc]
# Metadata to identify this config file. Do not change.
version = "1.9.2"
```

### Operating System

Windows

### streamrip version

1.9.3

### Screenshots and recordings

![image](https://user-images.githubusercontent.com/97956156/150724479-8a6263d7-6879-499f-891d-bc0eb64077a3.png)

**Comment by TofuOrganic** [comment]
Didnt realise this was a known issue, will just close this off.

**Comment by TofuOrganic** [comment]
Will leave open for tracking
