### ISSUE TITLE
Tidal download not working

### ISSUE THREAD

**Issue by kbruh** [nathom/streamrip#3]
```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/bin/rip", line 10, in <module>
    sys.exit(main())
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/streamrip/cli.py", line 212, in main
    cli(obj={})
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/click/core.py", line 1236, in invoke
    return Command.invoke(self, ctx)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/streamrip/cli.py", line 52, in cli
    core.handle_urls(kwargs["urls"])
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/streamrip/core.py", line 113, in handle_urls
    self.handle_item(source, url_type, item_id)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/streamrip/core.py", line 118, in handle_item
    client = self.get_client(source)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/streamrip/core.py", line 163, in get_client
    self.login(client)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/streamrip/core.py", line 176, in login
    client.login(**creds)
TypeError: login() got an unexpected keyword argument 'enabled'
```

**Comment by nathom** [comment]
Reset the config file with `rip --reset-config`. It should work after that.
