### ISSUE TITLE
[BUG] <SyntaxError: invalid syntax>

### ISSUE THREAD

**Issue by St0nehead** [nathom/streamrip#305]
### Describe the bug

Always get an error (see below)

### Command Used

```bash
rip --version
```

### Debug Traceback

```text
Mac-Pro:~ Donahue$ rip --version
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/bin/rip", line 5, in <module>
    from streamrip.cli import main
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/streamrip/cli.py", line 11, in <module>
    from .core import MusicDL
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/streamrip/core.py", line 22, in <module>
    from .downloader import Album, Artist, Label, Playlist, Track
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/streamrip/downloader.py", line 112
    if (u := kwargs.get("cover_url")) is not None:
          ^
SyntaxError: invalid syntax
```

### Config File

```toml
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/bin/rip", line 5, in <module>
    from streamrip.cli import main
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/streamrip/cli.py", line 11, in <module>
    from .core import MusicDL
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/streamrip/core.py", line 22, in <module>
    from .downloader import Album, Artist, Label, Playlist, Track
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/streamrip/downloader.py", line 112
    if (u := kwargs.get("cover_url")) is not None:
          ^
SyntaxError: invalid syntax
```

### Operating System

macOS Mojave 10.14.6 (18G9323)

### streamrip version

0.3

**Comment by nathom** [comment]
You need to upgrade python to 3.9 or above, and update streamrip with `pip3 install streamrip --upgrade`.
