### ISSUE TITLE
[FEATURE] Proxy support

### ISSUE THREAD

**Issue by pestapever** [nathom/streamrip#335]
### Is the feature request related to a problem. Please describe it.

I can't download behind http proxy.

### Describe the solution you would like.

Add a - - proxy parameter. Or https_proxy, https_proxy, no_proxy parameters as usual.

### Describe alternatives you've considered.

No alternatives.

**Comment by nathom** [comment]
I'll consider adding this. For now, try using environment variables.

Mac/Linux:

```bash
export HTTP_PROXY=10.10.1.10:3128
export HTTPS_PROXY=10.10.1.11:1080
export FTP_PROXY=10.10.1.10:3128
```

Windows:

```powershell
set http_proxy=10.10.1.10:3128
set https_proxy=10.10.1.11:1080
set ftp_proxy=10.10.1.10:3128
```

**Comment by pestapever** [comment]
Ok thanks. But if I run "rip url XYZ"

given 
SET HTTP_PROXY=name:password@hostname:port/
SET HTTPS_PROXY=name:password@hostname:port/

I got this:

Exception in thread Thread-1 (is_outdated):
Traceback (most recent call last):
  File "C:\Users\***\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "C:\Users\***\AppData\Local\Programs\Python\Python310\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\***\AppData\Local\Programs\Python\Python310\lib\site-packages\rip\cli.py", line 815, in is_outdated
Logging into qobuz
    r = requests.get("https://pypi.org/pypi/streamrip/json").json()
  File "C:\Users\***\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "C:\Users\***\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\***\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\***\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\***\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\adapters.py", line 456, in send
    conn = self.get_connection(request.url, proxies)
  File "C:\Users\***\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\adapters.py", line 348, in get_connection
    raise InvalidProxyURL(
requests.exceptions.InvalidProxyURL: Please check proxy URL. It is malformed and could be missing the host.

  InvalidProxyURL

  Please check proxy URL. It is malformed and could be missing the host.

  at ~\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\adapters.py:348 in get_connection
      344│         if proxy:
      345│             proxy = prepend_scheme_if_needed(proxy, "http")
      346│             proxy_url = parse_url(proxy)
      347│             if not proxy_url.host:
    → 348│                 raise InvalidProxyURL(
      349│                     "Please check proxy URL. It is malformed "
      350│                     "and could be missing the host."
      351│                 )
      352│             proxy_manager = self.proxy_manager_for(proxy)

If this was unexpected, please open a Bug Report at https://github.com/nathom/streamrip/issues/new/choose

**Comment by pestapever** [comment]
Close please
