### ISSUE TITLE
`ERROR:streamrip.clients:Problem getting JSON. Status code: 503

### ISSUE THREAD

**Issue by tretneo** [nathom/streamrip#34]
I upgraded to v0.3 to address an issue where album downloads would fail when cover.jpg couldn't be retrieved. After upgrading, I've been experiencing a lot of album download failures with an error similar to the following. Album downloads that fail with this error always seem to fail while others download just fine.

`ERROR:streamrip.clients:Problem getting JSON. Status code: 503
Traceback (most recent call last):
  File "/usr/local/bin/rip", line 10, in <module>
    sys.exit(main())
  File "/Library/Python/3.8/site-packages/streamrip/cli.py", line 237, in main
    cli(obj={})
  File "/Library/Python/3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Library/Python/3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Library/Python/3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Python/3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Python/3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Library/Python/3.8/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Library/Python/3.8/site-packages/streamrip/cli.py", line 145, in search
    core.download()
  File "/Library/Python/3.8/site-packages/streamrip/core.py", line 170, in download
    item.download(**arguments)
  File "/Library/Python/3.8/site-packages/streamrip/downloader.py", line 908, in download
    track.download(
  File "/Library/Python/3.8/site-packages/streamrip/downloader.py", line 204, in download
    dl_info = self.client.get_file_url(url_id, self.quality)
  File "/Library/Python/3.8/site-packages/streamrip/clients.py", line 209, in get_file_url
    return self._api_get_file_url(item_id, quality=quality)
  File "/Library/Python/3.8/site-packages/streamrip/clients.py", line 347, in _api_get_file_url
    response, status_code = self._api_request("track/getFileUrl", params)
  File "/Library/Python/3.8/site-packages/streamrip/clients.py", line 357, in _api_request
    return r.json(), r.status_code
  File "/Library/Python/3.8/site-packages/requests/models.py", line 900, in json
    return complexjson.loads(self.text, **kwargs)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 2 column 1 (char 1)`

**Comment by tretneo** [comment]
Update: This may have been due to a connection issue or something going on w/ Qobuz. It appears to have cleared up, all albums that were previously failing are now downloading fine.

**Comment by awsms** [comment]
I'm having this a lot, and this doesn't seem to be connected with Qobuz.
Is there a parameter to give to streamrip in order to immediatly retry to download a track that failed?
