### ISSUE TITLE
streamrip.exceptions.TooLargeCoverArt: Not suitable for Picture embed: 27.994118 MB

### ISSUE THREAD

**Issue by zzzzzozzzzz** [nathom/streamrip#37]
```
Traceback (most recent call last):
  File "/home/user/streamrip/bin/rip", line 33, in <module>
    sys.exit(load_entry_point('streamrip', 'console_scripts', 'rip')())
  File "/home/user/streamrip/streamrip/cli.py", line 258, in main
    cli(obj={})
  File "/home/user/streamrip/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/user/streamrip/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/user/streamrip/lib/python3.8/site-packages/click/core.py", line 1236, in invoke
    return Command.invoke(self, ctx)
  File "/home/user/streamrip/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/user/streamrip/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/user/streamrip/lib/python3.8/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/user/streamrip/streamrip/cli.py", line 103, in cli
    core.download()
  File "/home/user/streamrip/streamrip/core.py", line 182, in download
    item.download(**arguments)
  File "/home/user/streamrip/streamrip/downloader.py", line 910, in download
    cover = self.get_cover_obj(cover_path, quality)
  File "/home/user/streamrip/streamrip/downloader.py", line 622, in get_cover_obj
    raise TooLargeCoverArt(
streamrip.exceptions.TooLargeCoverArt: Not suitable for Picture embed: 27.994118 MB
```
```
artwork:
  embed: true
  embed_size: large
  download_size: original
  keep_embedded_cover: false
  keep_downloaded_cover: true
```

**Comment by nathom** [comment]
Please include the command and url you used.
