### ISSUE TITLE
ModuleNotFoundError: No module named 'packaging'

### ISSUE THREAD

**Issue by tretneo** [nathom/streamrip#38]
I was unable to open the config file after upgrading to v0.3.1 due to a missing module dependency.

`rip config --open                                     
Traceback (most recent call last):
  File "/usr/local/bin/rip", line 10, in <module>
    sys.exit(main())
  File "/Library/Python/3.8/site-packages/streamrip/cli.py", line 258, in main
    cli(obj={})
  File "/Library/Python/3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Library/Python/3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Library/Python/3.8/site-packages/click/core.py", line 1256, in invoke
    Command.invoke(self, ctx)
  File "/Library/Python/3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Python/3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Library/Python/3.8/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Library/Python/3.8/site-packages/streamrip/cli.py", line 61, in cli
    from packaging import version
ModuleNotFoundError: No module named 'packaging'`

I resolved this manually by installing the 'packaging' module

`sudo pip3 install packaging
WARNING: The directory '/Users/xxxxxx/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
WARNING: The directory '/Users/xxxxxx/Library/Caches/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting packaging
  Downloading https://files.pythonhosted.org/packages/3e/89/7ea760b4daa42653ece2380531c90f64788d979110a2ab51049d92f408af/packaging-20.9-py2.py3-none-any.whl (40kB)
     |████████████████████████████████| 40kB 5.1MB/s 
Collecting pyparsing>=2.0.2 (from packaging)
  Downloading https://files.pythonhosted.org/packages/8a/bb/488841f56197b13700afd5658fc279a2025a39e22449b7cf29864669b15d/pyparsing-2.4.7-py2.py3-none-any.whl (67kB)
     |████████████████████████████████| 71kB 7.2MB/s 
Installing collected packages: pyparsing, packaging
Successfully installed packaging-20.9 pyparsing-2.4.7
WARNING: You are using pip version 19.2.3, however version 21.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.`

**Comment by nathom** [comment]
Fixed in 0.3.2
