### ISSUE TITLE
track.get("media_number", 1) for track in resp["tracks"]["items"] KeyError: 'tracks'

### ISSUE THREAD

**Issue by tretneo** [nathom/streamrip#39]
Album searches fail after upgrade to v0.3.1. I uninstalled and reinstalled streamrip and started w/ a fresh config file, no luck.

`rip search 'mad season'                               
streamrip is up-to-date!
Logging into qobuz
Traceback (most recent call last):
  File "/usr/local/bin/rip", line 10, in <module>
    sys.exit(main())
  File "/Library/Python/3.8/site-packages/streamrip/cli.py", line 258, in main
    cli(obj={})
  File "/Library/Python/3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Library/Python/3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Library/Python/3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Python/3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Python/3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Library/Python/3.8/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Library/Python/3.8/site-packages/streamrip/cli.py", line 165, in search
    if core.interactive_search(query, kwargs["source"], kwargs["type"]):
  File "/Library/Python/3.8/site-packages/streamrip/core.py", line 322, in interactive_search
    results = tuple(self.search(source, query, media_type, limit=50))
  File "/Library/Python/3.8/site-packages/streamrip/core.py", line 278, in search
    yield MEDIA_CLASS[
  File "/Library/Python/3.8/site-packages/streamrip/downloader.py", line 729, in from_api
    info = cls._parse_get_resp(resp, client)
  File "/Library/Python/3.8/site-packages/streamrip/downloader.py", line 767, in _parse_get_resp
    track.get("media_number", 1) for track in resp["tracks"]["items"]
KeyError: 'tracks'
`

**Comment by nathom** [comment]
Fixed in 0.3.2.
