### ISSUE TITLE
Deezer not working

### ISSUE THREAD

**Issue by kbruh** [nathom/streamrip#4]
```Last login: Mon Mar 29 11:43:29 on ttys000
kevin@kevins-mbp ~ % rip -t /Users/kevin/Documents/Epic/urls.txt
Downloading Downtown Binary - 8MB
100%|███████████████████████████████████████| 140k/140k [00:00<00:00, 2.54MiB/s]

Downloading Downtown Binary - 8MB
100%|█████████████████████████████████████| 25.8M/25.8M [00:02<00:00, 12.2MiB/s]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/bin/rip", line 10, in <module>
    sys.exit(main())
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/streamrip/cli.py", line 212, in main
    cli(obj={})
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/click/core.py", line 1236, in invoke
    return Command.invoke(self, ctx)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/streamrip/cli.py", line 62, in cli
    core.download()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/streamrip/core.py", line 147, in download
    item.download(**arguments)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/streamrip/downloader.py", line 835, in download
    track.download(quality, folder, progress_bar, database=database)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/streamrip/downloader.py", line 231, in download
    if dl_info.get("enc_key"):
AttributeError: 'str' object has no attribute 'get'
kevin@kevins-mbp ~ % 
```

**Comment by kbruh** [comment]
How do I format this correctly?
