### ISSUE TITLE
Add support for Tidal mixes

### ISSUE THREAD

**Issue by nathom** [nathom/streamrip#5]

**Comment by kbruh** [comment]
Shouldn't this be closed?

**Comment by kbruh** [comment]
Wasn't this feature already added?

**Comment by nathom** [comment]
```
~/streamrip main
venv ❯ rip -u https://tidal.com/browse/mix/0052b7d91e5a9449c6a85c66eac706
A new version of streamrip is available! Run `pip3 install streamrip --upgrade` to update.
Logged into Tidal
Traceback (most recent call last):
  File "/Users/nathan/streamrip/venv/bin/rip", line 33, in <module>
    sys.exit(load_entry_point('streamrip', 'console_scripts', 'rip')())
  File "/Users/nathan/streamrip/streamrip/cli.py", line 297, in main
    cli(obj={})
  File "/Users/nathan/streamrip/venv/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/nathan/streamrip/venv/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/nathan/streamrip/venv/lib/python3.9/site-packages/click/core.py", line 1236, in invoke
    return Command.invoke(self, ctx)
  File "/Users/nathan/streamrip/venv/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/nathan/streamrip/venv/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/nathan/streamrip/venv/lib/python3.9/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/nathan/streamrip/streamrip/cli.py", line 96, in cli
    core.handle_urls(kwargs["urls"])
  File "/Users/nathan/streamrip/streamrip/core.py", line 103, in handle_urls
    self.handle_item(source, url_type, item_id)
  File "/Users/nathan/streamrip/streamrip/core.py", line 114, in handle_item
    assert media_type in MEDIA_TYPES, media_type
AssertionError
```
Nope.

**Comment by wrongoratbag** [comment]
Do I infer that downloading "mixes" from Tidal works, or that no one is interested in downloading same?
I've tried "rip url https://tidal.com/browse/mix/006fa43c4315bcad344a3c5530814a" several times and it doesn't work (for me at least) 
Everything else with streamrip works fine
