### ISSUE TITLE
KeyError: 'audioQuality'

### ISSUE THREAD

**Issue by zzzzzozzzzz** [nathom/streamrip#51]
```
Traceback (most recent call last):
  File "/home/user/streamrip/.venv/bin/rip", line 33, in <module>
    sys.exit(load_entry_point('streamrip', 'console_scripts', 'rip')())
  File "/home/user/streamrip/streamrip/cli.py", line 288, in main
    cli(obj={})
  File "/home/user/streamrip/.venv/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/user/streamrip/.venv/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/user/streamrip/.venv/lib/python3.9/site-packages/click/core.py", line 1236, in invoke
    return Command.invoke(self, ctx)
  File "/home/user/streamrip/.venv/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/user/streamrip/.venv/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/user/streamrip/.venv/lib/python3.9/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/user/streamrip/streamrip/cli.py", line 106, in cli
    core.download()
  File "/home/user/streamrip/streamrip/core.py", line 208, in download
    item.load_meta()
  File "/home/user/streamrip/streamrip/downloader.py", line 815, in load_meta
    self._load_tracks()
  File "/home/user/streamrip/streamrip/downloader.py", line 919, in _load_tracks
    Track.from_album_meta(album=self.meta, pos=i, client=self.client)
  File "/home/user/streamrip/streamrip/downloader.py", line 359, in from_album_meta
    meta = TrackMetadata(album=album, track=track, source=client.source)
  File "/home/user/streamrip/streamrip/metadata.py", line 97, in __init__
    self.add_track_meta(track)
  File "/home/user/streamrip/streamrip/metadata.py", line 247, in add_track_meta
    self.add_album_meta(track["album"])
  File "/home/user/streamrip/streamrip/metadata.py", line 168, in add_album_meta
    self.quality = TIDAL_Q_MAP[resp["audioQuality"]]
KeyError: 'audioQuality'
```

**Comment by nathom** [comment]
Please include the command and url that you used. Thanks.
