### ISSUE TITLE
[BUG] Unable to download a song from Deezer

### ISSUE THREAD

**Issue by bkdwt** [nathom/streamrip#524]
### Describe the bug

When I try to download "Habits (Stay High) (Oliver Nelson Remix)" I get this error: **Unable to stream Tove Lo - Habits (Stay High) (Oliver Nelson Remix). Message:**

### Command Used

```bash
rip url --max-quality 1 https://deezer.page.link/QraWDV9vg7fbnQ1p6
 rip url --max-quality 2 https://deezer.page.link/QraWDV9vg7fbnQ1p6
```

### Debug Traceback

```text
rip url --max-quality 1 https://deezer.page.link/QraWDV9vg7fbnQ1p6 -vvv
DEBUG:streamrip:Config loaded
Extracting IDs from Deezer dynamic link. Use urls of the form https://www.deezer.com/{country}/{type}/{id} for faster processing.
DEBUG:streamrip:Parsed urls: [('deezer', 'track', '79185305')]
DEBUG:streamrip:Searching for {'id': '79185305'} in database
DEBUG:streamrip:Executing SELECT EXISTS(SELECT 1 FROM downloads WHERE id=?)
DEBUG:streamrip:{'id': '79185305'}
DEBUG:streamrip:{'downloads': {'folder': 'C:\\Users\\mario\\StreamripDownloads', 'source_subdirectories': False, 'concurrency': {'enabled': True, 'max_connections': 3}}, 'qobuz': {'quality': 1, 'download_booklets': True, 'email': '', 'password': '', 'app_id': '', 'secrets': []}, 'tidal': {'quality': 1, 'download_videos': True, 'user_id': '', 'country_code': '', 'access_token': '', 'refresh_token': '', 'token_expiry': ''}, 'deezer': {'quality': 1, 'arl': '3d0178b19dfd14bdef949e03a7c541e6083b3d7f0e404cee187e3f6a82285633a72ad22c42275f6c6011fd68fb6c70b865e3a4af07f345f9d5afaec13dffacd923c3c6334f6705248fd7b6d53ef047a3df6938829f47c889058ec6c6c8a83080', 'use_deezloader': True, 'deezloader_warnings': True}, 'soundcloud': {'quality': 0, 'client_id': '', 'app_version': ''}, 'youtube': {'quality': 0, 'download_videos': False, 'video_downloads_folder': ''}, 'database': {'downloads': {'enabled': True, 'path': 'C:\\Users\\mario\\AppData\\Local\\streamrip\\streamrip\\downloads.db'}, 'failed_downloads': {'enabled': True, 'path': 'C:\\Users\\mario\\AppData\\Local\\streamrip\\streamrip\\failed_downloads.db'}}, 'conversion': {'enabled': False, 'codec': 'ALAC', 'sampling_rate': 48000, 'bit_depth': 24, 'lossy_bitrate': 320}, 'filters': {'extras': False, 'repeats': False, 'non_albums': False, 'features': False, 'non_studio_albums': False, 'non_remaster': False}, 'artwork': {'embed': True, 'size': 'large', 'max_width': -1, 'max_height': -1, 'keep_hires_cover': True}, 'metadata': {'set_playlist_to_album': True, 'new_playlist_tracknumbers': True, 'exclude': []}, 'filepaths': {'add_singles_to_folder': False, 'folder_format': '{albumartist} - {title} ({year}) [{container}] [{bit_depth}B-{sampling_rate}kHz]', 'track_format': '{tracknumber}. {artist} - {title}{explicit}', 'restrict_characters': False, 'truncate': True}, 'lastfm': {'source': 'qobuz', 'fallback_source': 'deezer'}, 'theme': {'progress_bar': 'dainty'}, 'misc': {'version': '1.9.6'}}
DEBUG:streamrip:Arguments from config: {'restrict_filenames': False, 'truncate_filenames': True, 'parent_folder': 'C:\\Users\\mario\\StreamripDownloads', 'folder_format': '{albumartist} - {title} ({year}) [{container}] [{bit_depth}B-{sampling_rate}kHz]', 'track_format': '{tracknumber}. {artist} - {title}{explicit}', 'embed_cover': True, 'embed_cover_size': 'large', 'keep_hires_cover': True, 'set_playlist_to_album': True, 'stay_temp': False, 'conversion': {'enabled': False, 'codec': 'ALAC', 'sampling_rate': 48000, 'bit_depth': 24, 'lossy_bitrate': 320}, 'concurrent_downloads': True, 'max_connections': 3, 'new_tracknumbers': True, 'download_videos': True, 'download_booklets': True, 'download_youtube_videos': False, 'youtube_video_downloads_folder': '', 'add_singles_to_folder': False, 'max_artwork_width': -1, 'max_artwork_height': -1, 'exclude_tags': []}
DEBUG:streamrip:Loading metadata
DEBUG:streamrip:{'id': 79185305, 'readable': False, 'title': 'Habits (Stay High) (Oliver Nelson Remix)', 'title_short': 'Habits (Stay High)', 'title_version': '(Oliver Nelson Remix)', 'isrc': 'SEUM71400750', 'link': 'https://www.deezer.com/track/79185305', 'share': 'https://www.deezer.com/track/79185305?utm_source=deezer&utm_content=track-79185305&utm_term=0_1704508387&utm_medium=web', 'duration': 252, 'track_position': 1, 'disk_number': 1, 'rank': 418825, 'release_date': '2014-06-17', 'explicit_lyrics': False, 'explicit_content_lyrics': 0, 'explicit_content_cover': 0, 'preview': 'https://cdns-preview-d.dzcdn.net/stream/c-db68e4f028e9e1731478268f272433cb-1.mp3', 'bpm': 116.1, 'gain': -7.1, 'available_countries': ['AT', 'CA', 'CH', 'DE', 'FR', 'JP', 'MX', 'US'], 'contributors': [{'id': 4103977, 'name': 'Tove Lo', 'link': 'https://www.deezer.com/artist/4103977', 'share': 'https://www.deezer.com/artist/4103977?utm_source=deezer&utm_content=artist-4103977&utm_term=0_1704508387&utm_medium=web', 'picture': 'https://api.deezer.com/artist/4103977/image', 'picture_small': 'https://e-cdns-images.dzcdn.net/images/artist/17ccd7da6a23da59066bef76cb89dbb7/56x56-000000-80-0-0.jpg', 'picture_medium': 'https://e-cdns-images.dzcdn.net/images/artist/17ccd7da6a23da59066bef76cb89dbb7/250x250-000000-80-0-0.jpg', 'picture_big': 'https://e-cdns-images.dzcdn.net/images/artist/17ccd7da6a23da59066bef76cb89dbb7/500x500-000000-80-0-0.jpg', 'picture_xl': 'https://e-cdns-images.dzcdn.net/images/artist/17ccd7da6a23da59066bef76cb89dbb7/1000x1000-000000-80-0-0.jpg', 'radio': True, 'tracklist': 'https://api.deezer.com/artist/4103977/top?limit=50', 'type': 'artist', 'role': 'Main'}], 'md5_image': '0cc8f04dc03e02e8334c468310893ec4', 'artist': {'id': 4103977, 'name': 'Tove Lo', 'link': 'https://www.deezer.com/artist/4103977', 'share': 'https://www.deezer.com/artist/4103977?utm_source=deezer&utm_content=artist-4103977&utm_term=0_1704508387&utm_medium=web', 'picture': 'https://api.deezer.com/artist/4103977/image', 'picture_small': 'https://e-cdns-images.dzcdn.net/images/artist/17ccd7da6a23da59066bef76cb89dbb7/56x56-000000-80-0-0.jpg', 'picture_medium': 'https://e-cdns-images.dzcdn.net/images/artist/17ccd7da6a23da59066bef76cb89dbb7/250x250-000000-80-0-0.jpg', 'picture_big': 'https://e-cdns-images.dzcdn.net/images/artist/17ccd7da6a23da59066bef76cb89dbb7/500x500-000000-80-0-0.jpg', 'picture_xl': 'https://e-cdns-images.dzcdn.net/images/artist/17ccd7da6a23da59066bef76cb89dbb7/1000x1000-000000-80-0-0.jpg', 'radio': True, 'tracklist': 'https://api.deezer.com/artist/4103977/top?limit=50', 'type': 'artist'}, 'album': {'id': 7875239, 'title': 'Habits (Stay High) (Oliver Nelson Remix)', 'link': 'https://www.deezer.com/album/7875239', 'cover': 'https://api.deezer.com/album/7875239/image', 'cover_small': 'https://e-cdns-images.dzcdn.net/images/cover/0cc8f04dc03e02e8334c468310893ec4/56x56-000000-80-0-0.jpg', 'cover_medium': 'https://e-cdns-images.dzcdn.net/images/cover/0cc8f04dc03e02e8334c468310893ec4/250x250-000000-80-0-0.jpg', 'cover_big': 'https://e-cdns-images.dzcdn.net/images/cover/0cc8f04dc03e02e8334c468310893ec4/500x500-000000-80-0-0.jpg', 'cover_xl': 'https://e-cdns-images.dzcdn.net/images/cover/0cc8f04dc03e02e8334c468310893ec4/1000x1000-000000-80-0-0.jpg', 'md5_image': '0cc8f04dc03e02e8334c468310893ec4', 'release_date': '2013-01-01', 'tracklist': 'https://api.deezer.com/album/7875239/tracks', 'type': 'album'}, 'type': 'track'}
Downloading Tove Lo - Habits (Stay High) (Oliver Nelson Remix)

DEBUG:streamrip:Track meta formatter {'tracknumber': 1, 'artist': 'Tove Lo', 'albumartist': None, 'composer': None, 'title': 'Habits (Stay High) (Oliver Nelson Remix)', 'albumcomposer': None, 'explicit': False}
DEBUG:streamrip:Formatter keys: {tracknumber}. {artist} - {title}{explicit}
DEBUG:streamrip:'tracknumber'
DEBUG:streamrip:1
DEBUG:streamrip:2
DEBUG:streamrip:'artist'
DEBUG:streamrip:Tove Lo
DEBUG:streamrip:1
DEBUG:streamrip:'title'
DEBUG:streamrip:Habits (Stay High) (Oliver Nelson Remix)
DEBUG:streamrip:1
DEBUG:streamrip:'explicit'
DEBUG:streamrip:False
DEBUG:streamrip:3
DEBUG:streamrip:Formatted path: C:\Users\mario\StreamripDownloads\01. Tove Lo - Habits (Stay High) (Oliver Nelson Remix).mp3
DEBUG:streamrip:Downloading cover from https://e-cdns-images.dzcdn.net/images/cover/0cc8f04dc03e02e8334c468310893ec4/500x500-000000-80-0-0.jpg
Cover |███████████████████████████████████████████████████████████████████████████████████████| 00:00 left at 1.24MB/s
--- Logging error ---
Traceback (most recent call last):
  File "C:\Users\mario\AppData\Local\Programs\Python\Python311\Lib\logging\__init__.py", line 1113, in emit
    stream.write(msg + self.terminator)
  File "C:\Users\mario\AppData\Local\Programs\Python\Python311\Lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeEncodeError: 'charmap' codec can't encode characters in position 408-412: character maps to <undefined>
Call stack:
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\mario\AppData\Local\Programs\Python\Python311\Scripts\rip.exe\__main__.py", line 7, in <module>
    sys.exit(main())
  File "C:\Users\mario\AppData\Local\Programs\Python\Python311\Lib\site-packages\rip\cli.py", line 841, in main
    application.run()
  File "C:\Users\mario\AppData\Local\Programs\Python\Python311\Lib\site-packages\cleo\application.py", line 330, in run
    exit_code = self._run(io)
  File "C:\Users\mario\AppData\Local\Programs\Python\Python311\Lib\site-packages\rip\cli.py", line 762, in _run
    super()._run(io)
  File "C:\Users\mario\AppData\Local\Programs\Python\Python311\Lib\site-packages\cleo\application.py", line 425, in _run
    exit_code = self._run_command(command, io)
  File "C:\Users\mario\AppData\Local\Programs\Python\Python311\Lib\site-packages\cleo\application.py", line 432, in _run_command
    return command.run(io)
  File "C:\Users\mario\AppData\Local\Programs\Python\Python311\Lib\site-packages\cleo\commands\base_command.py", line 118, in run
    status_code = self.execute(io)
  File "C:\Users\mario\AppData\Local\Programs\Python\Python311\Lib\site-packages\cleo\commands\command.py", line 85, in execute
    return self.handle()
  File "C:\Users\mario\AppData\Local\Programs\Python\Python311\Lib\site-packages\rip\cli.py", line 125, in handle
    core.download()
  File "C:\Users\mario\AppData\Local\Programs\Python\Python311\Lib\site-packages\rip\core.py", line 314, in download
    item.download(**arguments)
  File "C:\Users\mario\AppData\Local\Programs\Python\Python311\Lib\site-packages\streamrip\media.py", line 298, in download
    dl_info = self.client.get_file_url(url_id, self.quality)
  File "C:\Users\mario\AppData\Local\Programs\Python\Python311\Lib\site-packages\streamrip\clients.py", line 554, in get_file_url
    logger.debug("Track info: %s", track_info)
Message: 'Track info: %s'
Arguments: {'ALB_ID': '7875239', 'ALB_PICTURE': '0cc8f04dc03e02e8334c468310893ec4', 'ALB_TITLE': 'Habits (Stay High) (Oliver Nelson Remix)', 'ARTISTS': [{'ART_ID': '4103977', 'ROLE_ID': '0', 'ARTISTS_SONGS_ORDER': '1', 'ART_NAME': 'Tove Lo', 'ARTIST_IS_DUMMY': False, 'ART_PICTURE': '17ccd7da6a23da59066bef76cb89dbb7', 'RANK': '715330', 'LOCALES': {'lang_en': {'name': 'Tove Lo'}, 'lang_ja-hrkt': {'name': 'トーブロー'}, 'lang_ja-jpan': {'name': 'トーヴ・ロー'}, 'lang_ja-kana': {'name': 'トーヴロー'}, 'lang_ja': {'name': 'TOVE LO'}, 'lang_ar': {'name': 'توفي لو'}}, '__TYPE__': 'artist'}], 'ART_ID': '4103977', 'ART_NAME': 'Tove Lo', 'ARTIST_IS_DUMMY': False, 'DIGITAL_RELEASE_DATE': '2014-06-17', 'DISK_NUMBER': '1', 'DURATION': '252', 'EXPLICIT_LYRICS': '0', 'EXPLICIT_TRACK_CONTENT': {'EXPLICIT_LYRICS_STATUS': 0, 'EXPLICIT_COVER_STATUS': 0}, 'FALLBACK': {'ALB_ID': '8722197', 'ALB_PICTURE': 'a8dba84be1bb971a7148cc41630ef41a', 'ALB_TITLE': 'Truth Serum', 'ARTISTS': [{'ART_ID': '4103977', 'ROLE_ID': '0', 'ARTISTS_SONGS_ORDER': '1', 'ART_NAME': 'Tove Lo', 'ARTIST_IS_DUMMY': False, 'ART_PICTURE': '17ccd7da6a23da59066bef76cb89dbb7', 'RANK': '715330', 'LOCALES': {'lang_en': {'name': 'Tove Lo'}, 'lang_ja-hrkt': {'name': 'トーブロー'}, 'lang_ja-jpan': {'name': 'トーヴ・ロー'}, 'lang_ja-kana': {'name': 'トーヴロー'}, 'lang_ja': {'name': 'TOVE LO'}, 'lang_ar': {'name': 'توفي لو'}}, '__TYPE__': 'artist'}], 'ART_ID': '4103977', 'ART_NAME': 'Tove Lo', 'ARTIST_IS_DUMMY': False, 'DIGITAL_RELEASE_DATE': '2014-09-29', 'DISK_NUMBER': '1', 'DURATION': '252', 'EXPLICIT_LYRICS': '0', 'EXPLICIT_TRACK_CONTENT': {'EXPLICIT_LYRICS_STATUS': 0, 'EXPLICIT_COVER_STATUS': 0}, 'GENRE_ID': '27', 'HIERARCHICAL_TITLE': '', 'ISRC': 'SEUM71400750', 'LYRICS_ID': 1824570, 'PHYSICAL_RELEASE_DATE': '2014-01-01', 'PROVIDER_ID': '427', 'RANK': '244857', 'SMARTRADIO': 0, 'SNG_CONTRIBUTORS': {'main_artist': ['Tove Lo'], 'artist': ['Jakob Jerlström', 'Ludvig Söderberg', 'Tove Lo', 'Filip Runesson'], 'composer': ['Jakob Jerlström', 'Ludvig Söderberg', 'Tove Lo', 'Daniel Ledinsky'], 'remixer': ['Oliver Nelson']}, 'SNG_ID': '86454215', 'SNG_TITLE': 'Habits (Stay High)', 'STATUS': 1, 'TRACK_NUMBER': '3', 'USER_ID': 0, 'VERSION': '(Oliver Nelson Remix)', 'MD5_ORIGIN': '76072894708d4b9d9fd2af57e5951fcd', 'FILESIZE_AAC_64': '0', 'FILESIZE_MP3_64': '0', 'FILESIZE_MP3_128': '4034724', 'FILESIZE_MP3_256': '0', 'FILESIZE_MP3_320': '10086564', 'FILESIZE_FLAC': '31725351', 'FILESIZE': '4034724', 'GAIN': '-7.1', 'MEDIA_VERSION': '1', 'TRACK_TOKEN': 'AAAAAWWYu-RlmdUkEcEmIL8vHAjrlBHUfgFWrnxO4_k2evjqC3TRtbScHJdinZIUGk8MqJQqb5aAKgeDDSy7LSS1OMU6Ddvj5th2vOz48Y_GgWze3Ser4kl8-H-Cp5NHLQu5Nz5o_ZB_uQWgvKj6Gg', 'TRACK_TOKEN_EXPIRE': 1704580388, 'MEDIA': [{'TYPE': 'preview', 'HREF': 'http://cdn-preview-6.deezer.com/stream/c-6c4e1229da52482966e365717f368777-1.mp3'}], 'RIGHTS': {'STREAM_ADS_AVAILABLE': True, 'STREAM_ADS': '2000-01-01', 'STREAM_SUB_AVAILABLE': True, 'STREAM_SUB': '2000-01-01'}, '__TYPE__': 'song'}, 'GENRE_ID': '27', 'HIERARCHICAL_TITLE': '', 'ISRC': 'SEUM71400750', 'LYRICS_ID': 1824570, 'PHYSICAL_RELEASE_DATE': '2013-01-01', 'PROVIDER_ID': '427', 'RANK': '418825', 'SMARTRADIO': 0, 'SNG_CONTRIBUTORS': {'main_artist': ['Tove Lo'], 'artist': ['Jakob Jerlström', 'Ludvig Söderberg', 'Tove Lo', 'Filip Runesson'], 'composer': ['Jakob Jerlström', 'Ludvig Söderberg', 'Tove Lo', 'Daniel Ledinsky'], 'remixer': ['Oliver Nelson']}, 'SNG_ID': '79185305', 'SNG_TITLE': 'Habits (Stay High)', 'STATUS': 1, 'TRACK_NUMBER': '1', 'USER_ID': 0, 'VERSION': '(Oliver Nelson Remix)', 'MD5_ORIGIN': 'dbce5581d2c76590022f082d76f7723f', 'FILESIZE_AAC_64': '0', 'FILESIZE_MP3_64': '0', 'FILESIZE_MP3_128': '4033060', 'FILESIZE_MP3_256': '0', 'FILESIZE_MP3_320': '10086572', 'FILESIZE_FLAC': '31723867', 'FILESIZE': '4033060', 'GAIN': '-7.1', 'MEDIA_VERSION': '1', 'TRACK_TOKEN': 'AAAAAWWYu-RlmdUkaJ0U9cFDEgRxkIhXdOf2xkgr1aCOypb93B4L6oH9cgwiSZFquE2t-soqnuewwY1ju2kCmF-Xzdcqb9yQYE8DDyR0N5VNCCHkW3rGMeBpobFij5jYHGQDbO1hR5PROqeF6npukAikynA', 'TRACK_TOKEN_EXPIRE': 1704580388, 'MEDIA': [{'TYPE': 'preview', 'HREF': 'http://cdn-preview-d.deezer.com/stream/c-db68e4f028e9e1731478268f272433cb-1.mp3'}], 'RIGHTS': {}, '__TYPE__': 'song'}
DEBUG:streamrip:Track info: {'ALB_ID': '7875239', 'ALB_PICTURE': '0cc8f04dc03e02e8334c468310893ec4', 'ALB_TITLE': 'Habits (Stay High) (Oliver Nelson Remix)', 'ARTISTS': [{'ART_ID': '4103977', 'ROLE_ID': '0', 'ARTISTS_SONGS_ORDER': '1', 'ART_NAME': 'Tove Lo', 'ARTIST_IS_DUMMY': False, 'ART_PICTURE': '17ccd7da6a23da59066bef76cb89dbb7', 'RANK': '715330', 'LOCALES': {'lang_en': {'name': 'Tove Lo'}, 'lang_ja-hrkt': {'name': 'トーブロー'}, 'lang_ja-jpan': {'name': 'トーヴ・ロー'}, 'lang_ja-kana': {'name': 'トーヴロー'}, 'lang_ja': {'name': 'TOVE LO'}, 'lang_ar': {'name': 'توفي لو'}}, '__TYPE__': 'artist'}], 'ART_ID': '4103977', 'ART_NAME': 'Tove Lo', 'ARTIST_IS_DUMMY': False, 'DIGITAL_RELEASE_DATE': '2014-06-17', 'DISK_NUMBER': '1', 'DURATION': '252', 'EXPLICIT_LYRICS': '0', 'EXPLICIT_TRACK_CONTENT': {'EXPLICIT_LYRICS_STATUS': 0, 'EXPLICIT_COVER_STATUS': 0}, 'FALLBACK': {'ALB_ID': '8722197', 'ALB_PICTURE': 'a8dba84be1bb971a7148cc41630ef41a', 'ALB_TITLE': 'Truth Serum', 'ARTISTS': [{'ART_ID': '4103977', 'ROLE_ID': '0', 'ARTISTS_SONGS_ORDER': '1', 'ART_NAME': 'Tove Lo', 'ARTIST_IS_DUMMY': False, 'ART_PICTURE': '17ccd7da6a23da59066bef76cb89dbb7', 'RANK': '715330', 'LOCALES': {'lang_en': {'name': 'Tove Lo'}, 'lang_ja-hrkt': {'name': 'トーブロー'}, 'lang_ja-jpan': {'name': 'トーヴ・ロー'}, 'lang_ja-kana': {'name': 'トーヴロー'}, 'lang_ja': {'name': 'TOVE LO'}, 'lang_ar': {'name': 'توفي لو'}}, '__TYPE__': 'artist'}], 'ART_ID': '4103977', 'ART_NAME': 'Tove Lo', 'ARTIST_IS_DUMMY': False, 'DIGITAL_RELEASE_DATE': '2014-09-29', 'DISK_NUMBER': '1', 'DURATION': '252', 'EXPLICIT_LYRICS': '0', 'EXPLICIT_TRACK_CONTENT': {'EXPLICIT_LYRICS_STATUS': 0, 'EXPLICIT_COVER_STATUS': 0}, 'GENRE_ID': '27', 'HIERARCHICAL_TITLE': '', 'ISRC': 'SEUM71400750', 'LYRICS_ID': 1824570, 'PHYSICAL_RELEASE_DATE': '2014-01-01', 'PROVIDER_ID': '427', 'RANK': '244857', 'SMARTRADIO': 0, 'SNG_CONTRIBUTORS': {'main_artist': ['Tove Lo'], 'artist': ['Jakob Jerlström', 'Ludvig Söderberg', 'Tove Lo', 'Filip Runesson'], 'composer': ['Jakob Jerlström', 'Ludvig Söderberg', 'Tove Lo', 'Daniel Ledinsky'], 'remixer': ['Oliver Nelson']}, 'SNG_ID': '86454215', 'SNG_TITLE': 'Habits (Stay High)', 'STATUS': 1, 'TRACK_NUMBER': '3', 'USER_ID': 0, 'VERSION': '(Oliver Nelson Remix)', 'MD5_ORIGIN': '76072894708d4b9d9fd2af57e5951fcd', 'FILESIZE_AAC_64': '0', 'FILESIZE_MP3_64': '0', 'FILESIZE_MP3_128': '4034724', 'FILESIZE_MP3_256': '0', 'FILESIZE_MP3_320': '10086564', 'FILESIZE_FLAC': '31725351', 'FILESIZE': '4034724', 'GAIN': '-7.1', 'MEDIA_VERSION': '1', 'TRACK_TOKEN': 'AAAAAWWYu-RlmdUkEcEmIL8vHAjrlBHUfgFWrnxO4_k2evjqC3TRtbScHJdinZIUGk8MqJQqb5aAKgeDDSy7LSS1OMU6Ddvj5th2vOz48Y_GgWze3Ser4kl8-H-Cp5NHLQu5Nz5o_ZB_uQWgvKj6Gg', 'TRACK_TOKEN_EXPIRE': 1704580388, 'MEDIA': [{'TYPE': 'preview', 'HREF': 'http://cdn-preview-6.deezer.com/stream/c-6c4e1229da52482966e365717f368777-1.mp3'}], 'RIGHTS': {'STREAM_ADS_AVAILABLE': True, 'STREAM_ADS': '2000-01-01', 'STREAM_SUB_AVAILABLE': True, 'STREAM_SUB': '2000-01-01'}, '__TYPE__': 'song'}, 'GENRE_ID': '27', 'HIERARCHICAL_TITLE': '', 'ISRC': 'SEUM71400750', 'LYRICS_ID': 1824570, 'PHYSICAL_RELEASE_DATE': '2013-01-01', 'PROVIDER_ID': '427', 'RANK': '418825', 'SMARTRADIO': 0, 'SNG_CONTRIBUTORS': {'main_artist': ['Tove Lo'], 'artist': ['Jakob Jerlström', 'Ludvig Söderberg', 'Tove Lo', 'Filip Runesson'], 'composer': ['Jakob Jerlström', 'Ludvig Söderberg', 'Tove Lo', 'Daniel Ledinsky'], 'remixer': ['Oliver Nelson']}, 'SNG_ID': '79185305', 'SNG_TITLE': 'Habits (Stay High)', 'STATUS': 1, 'TRACK_NUMBER': '1', 'USER_ID': 0, 'VERSION': '(Oliver Nelson Remix)', 'MD5_ORIGIN': 'dbce5581d2c76590022f082d76f7723f', 'FILESIZE_AAC_64': '0', 'FILESIZE_MP3_64': '0', 'FILESIZE_MP3_128': '4033060', 'FILESIZE_MP3_256': '0', 'FILESIZE_MP3_320': '10086572', 'FILESIZE_FLAC': '31723867', 'FILESIZE': '4033060', 'GAIN': '-7.1', 'MEDIA_VERSION': '1', 'TRACK_TOKEN': 'AAAAAWWYu-RlmdUkaJ0U9cFDEgRxkIhXdOf2xkgr1aCOypb93B4L6oH9cgwiSZFquE2t-soqnuewwY1ju2kCmF-Xzdcqb9yQYE8DDyR0N5VNCCHkW3rGMeBpobFij5jYHGQDbO1hR5PROqeF6npukAikynA', 'TRACK_TOKEN_EXPIRE': 1704580388, 'MEDIA': [{'TYPE': 'preview', 'HREF': 'http://cdn-preview-d.deezer.com/stream/c-db68e4f028e9e1731478268f272433cb-1.mp3'}], 'RIGHTS': {}, '__TYPE__': 'song'}
DEBUG:streamrip:WrongGeolocation()
Unable to stream Tove Lo - Habits (Stay High) (Oliver Nelson Remix). Message:
DEBUG:streamrip:Executing INSERT INTO failed_downloads (source, media_type, id) VALUES (?, ?, ?)
DEBUG:streamrip:Items to add: ('deezer', 'track', '79185305')
DEBUG:streamrip:UNIQUE constraint failed: failed_downloads.id
```

### Config File

```toml
[downloads]
# Folder where tracks are downloaded to
folder = "C:\\Users\\mario\\StreamripDownloads"
# Put Qobuz albums in a 'Qobuz' folder, Tidal albums in 'Tidal' etc.
source_subdirectories = false




[downloads.concurrency]
# Download (and convert) tracks all at once, instead of sequentially. 
# If you are converting the tracks, or have fast internet, this will 
# substantially improve processing speed.
enabled = true
# The maximum number of tracks to download at once
# If you have very fast internet, you will benefit from a higher value,
# A value that is too high for your bandwidth may cause slowdowns
max_connections = 3




[qobuz]
# 1: 320kbps MP3, 2: 16/44.1, 3: 24/<=96, 4: 24/>=96
quality = 3
# This will download booklet pdfs that are included with some albums
download_booklets = true

email = ""
# This is an md5 hash of the plaintext password
password = ""
# Do not change
app_id = ""
# Do not change
secrets = []




[tidal]
# 0: 256kbps AAC, 1: 320kbps AAC, 2: 16/44.1 "HiFi" FLAC, 3: 24/44.1 "MQA" FLAC
quality = 3
# This will download videos included in Video Albums.
download_videos = true

# Do not change any of the fields below
user_id = ""
country_code = ""
access_token = ""
refresh_token = ""
# Tokens last 1 week after refresh. This is the Unix timestamp of the expiration
# time. If you haven't used streamrip in more than a week, you may have to log
# in again using `rip config --tidal`
token_expiry = ""




[deezer]
# 0, 1, or 2
# This only applies to paid Deezer subscriptions. Those using deezloader
# are automatically limited to quality = 1
quality = 2
# An authentication cookie that allows streamrip to use your Deezer account
# See https://github.com/nathom/streamrip/wiki/Finding-Your-Deezer-ARL-Cookie
# for instructions on how to find this
arl = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
# This allows for free 320kbps MP3 downloads from Deezer
# If an arl is provided, deezloader is never used
use_deezloader = true
# This warns you when the paid deezer account is not logged in and rip falls
# back to deezloader, which is unreliable
deezloader_warnings = true




[soundcloud]
# Only 0 is available for now
quality = 0
# This changes periodically, so it needs to be updated
client_id = ""
app_version = ""




[youtube]
# Only 0 is available for now
quality = 0
# Download the video along with the audio
download_videos = false
# The path to download the videos to
video_downloads_folder = ""

# This stores a list of item IDs so that repeats are not downloaded.



[database.downloads]
enabled = true
path = "C:\\Users\\mario\\AppData\\Local\\streamrip\\streamrip\\downloads.db"

# If a download fails, the item ID is stored here. Then, `rip repair` can be
# called to retry the downloads



[database.failed_downloads]
enabled = true
path = "C:\\Users\\mario\\AppData\\Local\\streamrip\\streamrip\\failed_downloads.db"

# Convert tracks to a codec after downloading them.



[conversion]
enabled = false
# FLAC, ALAC, OPUS, MP3, VORBIS, or AAC
codec = "ALAC"
# In Hz. Tracks are downsampled if their sampling rate is greater than this. 
# Value of 48000 is recommended to maximize quality and minimize space
sampling_rate = 48000
# Only 16 and 24 are available. It is only applied when the bit depth is higher
# than this value.
bit_depth = 24
# Only applicable for lossy codecs
lossy_bitrate = 320

# Filter a Qobuz artist's discography. Set to 'true' to turn on a filter.



[filters]
# Remove Collectors Editions, live recordings, etc.
extras = false
# Picks the highest quality out of albums with identical titles.
repeats = false
# Remove EPs and Singles
non_albums = false
# Remove albums whose artist is not the one requested
features = false
# Skip non studio albums
non_studio_albums = false
# Only download remastered albums
non_remaster = false




[artwork]
# Write the image to the audio file
embed = true
# The size of the artwork to embed. Options: thumbnail, small, large, original.
# "original" images can be up to 30MB, and may fail embedding. 
# Using "large" is recommended.
size = "large"
# Both of these options limit the size of the embedded artwork. If their values
# are larger than the actual dimensions of the image, they will be ignored.
# If either value is -1, the image is left untouched.
max_width = -1
max_height = -1
# Save the cover image at the highest quality as a seperate jpg file
keep_hires_cover = true




[metadata]
# Sets the value of the 'ALBUM' field in the metadata to the playlist's name. 
# This is useful if your music library software organizes tracks based on album name.
set_playlist_to_album = true
# Replaces the original track's tracknumber with it's position in the playlist
new_playlist_tracknumbers = true
# The following metadata tags won't be applied
# See https://github.com/nathom/streamrip/wiki/Metadata-Tag-Names for more info
exclude = []

# Changes the folder and file names generated by streamrip.



[filepaths]
# Create folders for single tracks within the downloads directory using the folder_format
# template
add_singles_to_folder = false
# Available keys: "albumartist", "title", "year", "bit_depth", "sampling_rate",
# "container", "id", and "albumcomposer"
folder_format = "{albumartist} - {title} ({year}) [{container}] [{bit_depth}B-{sampling_rate}kHz]"
# Available keys: "tracknumber", "artist", "albumartist", "composer", "title",
# and "albumcomposer"
track_format = "{tracknumber}. {artist} - {title}{explicit}"
# Only allow printable ASCII characters in filenames.
restrict_characters = false
# Truncate the filename if it is greater than 120 characters
# Setting this to false may cause downloads to fail on some systems
truncate = true


# Last.fm playlists are downloaded by searching for the titles of the tracks



[lastfm]
# The source on which to search for the tracks.
source = "qobuz"
# If no results were found with the primary source, the item is searched for 
# on this one.
fallback_source = "deezer"




[theme]
# Options: "dainty" or "plain"
progress_bar = "dainty"




[misc]
# Metadata to identify this config file. Do not change.
version = "1.9.6"
```

### Operating System

Windows 11

### streamrip version

1.9.7

**Comment by nathom** [comment]
Try again on the latest version. It works on my machine.
