### ISSUE TITLE
Index error on Tidal Download

### ISSUE THREAD

**Issue by Hecubus** [nathom/streamrip#54]
**Traceback** 
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/bin/rip", line 8, in <module>
    sys.exit(main())
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/streamrip/cli.py", line 288, in main
    cli(obj={})
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/click/core.py", line 1236, in invoke
    return Command.invoke(self, ctx)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/streamrip/cli.py", line 106, in cli
    core.download()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/streamrip/core.py", line 208, in download
    item.load_meta()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/streamrip/downloader.py", line 835, in load_meta
    self._load_tracks()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/streamrip/downloader.py", line 1027, in _load_tracks
    Track.from_album_meta(album=self.meta, pos=i, client=self.client)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/streamrip/downloader.py", line 374, in from_album_meta
    track = tracklist[pos]
IndexError: list index out of range

**Command executed:**
rip -u https://tidal.com/browse/album/29780735
streamrip is up-to-date!
Logged into Tidal

**Version verified as 0.4.2:**
pip3 install streamrip --upgrade
Requirement already satisfied: streamrip in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (0.4.2)

**Comment by nathom** [comment]
It works perfectly for me. Maybe it's a network error on your part. Please run `rip -u https://tidal.com/browse/album/29780735 --debug` and send me the file at `~/Library/Application Support/streamrip/streamrip.log` so that I can investigate further.

**Comment by Hecubus** [comment]
[streamrip.log](https://github.com/nathom/streamrip/files/6339310/streamrip.log)

**Comment by nathom** [comment]
Does the issue persist after the latest update?

**Comment by Hecubus** [comment]
Great idea! The problem was still there when I ran the log dump, but upgrading to V0.4.4 did result in a successful run. I'll close this issue.
