### ISSUE TITLE
SyntaxError: invalid syntax (using Deezer)

### ISSUE THREAD

**Issue by VikasRana** [nathom/streamrip#64]
Getting this.

`Traceback (most recent call last):
  File "c:\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Python37\Scripts\rip.exe\__main__.py", line 4, in <module>
  File "c:\python37\lib\site-packages\streamrip\cli.py", line 11, in <module>
    from .core import MusicDL
  File "c:\python37\lib\site-packages\streamrip\core.py", line 22, in <module>
    from .downloader import Album, Artist, Label, Playlist, Track
  File "c:\python37\lib\site-packages\streamrip\downloader.py", line 112
    if (u := kwargs.get("cover_url")) is not None:
          ^
SyntaxError: invalid syntax`

**Comment by nathom** [comment]
You need to upgrade your version of python.
