### ISSUE TITLE
[BUG] <cmd prompt ran across issue>

### ISSUE THREAD

**Issue by univon** [nathom/streamrip#783]
### Describe the bug

I tried to install on command prompt but ran across a error code

### Command Used

```bash
error: subprocess-exited-with-error
X
Getting requirements to build wheel did not run successfully
exit code: 1
24
output:
ne
Traceback (most recent call last):
File "C:\Users\elija\AppData\Local\Programs\Python\Python313\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <modulex
main(
NNNNAA
File "C;\Users) lelijalppDatalLocall \Programs \Python\Python313\Lib\site- packages\pipl vendor \pyproject_ hooks in_ _process\ in _process.py", line 335, in main
json out[ return val'] hook( **hook_ anput[
AA A
NNNNA
File "C:\Users\elija\AppData\Local\Programs\Python\Python313\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requird
for_build_wheel
return hook(config_settings)
File "C;\Users\elija\AppData\Local\Temp\pip-build-env-r2p0ydwo\overlay\Lib\site-packages\setuptools\build_meta.py", line 334, in get_requires_for_build_wheel
return self,_get_build_requires(config_settings, requirements-[])
NNNNNI
file "C;\Users\elija\AppData\Local\Temp\pip-build-env-r2p0ydwo\overlay\Lib\site-packages\setuptools\build_meta.py", line 304, in _get_build_requires
self,run_setup()
NNNNNNNNNNI INNNA/
File "C;\Users\elija\AppData\Local\Temp\pip-build-env-r2p0ydwo\overlay\Lib\site-packages\setuptools\build_meta.py", line 522, in run_setup
super().run_setup(setup_script-setup_script)
File "C:\Users\elija\AppData\Local\Temp\pip-build-env-r2p0ydwo\overlay\Lib\site-packages\setuptools\build_meta.py", line 320, in run_setup
exec(code, locals())
NNNNA
file "<string>", line 29, in <module>
File "<string>", line 26, in get_version
T version
KeyError:
end of output
note: This error originates from a subprocess, and is likely not a problem with pip.
irror: subprocess-exited-with-error
Getting requirements to build wheel did not run successfully.
exit code: 1
See above for output
```

### Debug Traceback

```text
N/A
```

### Config File

```toml
N/A
```

### Operating System

Windows

### streamrip version

2.0.5

### Additional context

I was on github via HP 15 laptop

**Comment by univon** [comment]
I'm actually on win11 pro and now ran across another error message like this "ERROR: Could not find a version that satisfies the requirement windows-curses<3.0.0,>=2.2.0: sys_platform == "win32" or
bys_platform == "cygwin" (from streamrip) (from versions: none)
ERROR: NO matching distribution found for windows-curses<3.0.0, >-2.2.0; sys_platform
Roblox
"win32" Or sys_ _platform " "cygw"

**Comment by karkcoder** [comment]
> I'm actually on win11 pro and now ran across another error message like this "ERROR: Could not find a version that satisfies the requirement windows-curses<3.0.0,>=2.2.0: sys_platform == "win32" or bys_platform == "cygwin" (from streamrip) (from versions: none) ERROR: NO matching distribution found for windows-curses<3.0.0, >-2.2.0; sys_platform == "win32" Or sys_ _platform " "cygwin" . I ran across both problems whenever I used this cmd "pip3 install streamrip --upgrade"

https://github.com/nathom/streamrip/issues/768

**Comment by univon** [comment]
I used all of the commands and then this pop up "using cached pillow 9.5.0" and error code "File "C:\Users\elija\AppData\Local\Temp\pip-build-env-_99ukqv7\overlay\Lib\site-packages
\setuptools\build_meta.py", line 304, in _get_build_requires
self.run_setup()
File "C:\Users\elija\AppData\Local\Temp\pip-build-env-_99ukqv7\overlay\Lib\site-packages
\setuptools\build_meta.py", line 522, in run_setup
super().run_setup(setup_script=setup_script)
File "C:\Users\elija\AppData\Local\Temp\pip-build-env-_99ukqv7\overlay\Lib\site-packages
\setuptools\build_meta.py", line 320, in run_setup
exec(code, locals())
File "<string>", line 29, in <module>
File "<string>", line 26, in get_version
KeyError: '_version_
[end of output] and this Getting requirements to build wheel ... error
error: subprocess-exited-with-error
x Getting requirements to build wheel did not run successfully
exit code: 1
[24 lines of output]
Traceback (most recent call last):
File "C:\Users\elija\AppData\Local\Programs\Python\Python313\Lib\site-packages\pipl_vend
or \pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
main()
File "C:\Users\elija\AppData\Local\Programs\Python\Python313\Lib\site-packages\pip\_vend
or\pyproject_hooks\in_process\_in_process.py", line 335, in main
json_out['return_val'] = hook(*+hook_input[ 'kwargs'])
AA
File "C:\Users\elija\AppData\Local\Programs\Python\Python313\Lib\site-packages\pipl_vend
or \pyproject _hooks\in_processlin_process.py", line 118, in get_requires_for build_wheel
return hook(config_settings)
File "C:\Users\elija\AppData\Local\Temp\pip-build-env-_99ukqv7\overlay\Lib\site-packages"
