### ISSUE TITLE
config.toml is not included in the pip package.

### ISSUE THREAD

**Issue by Vencorr** [nathom/streamrip#93]
## Bug Report

**Current Behavior**
Pip install does not include the default config.toml, causing the program to crash on a new install (or upgraded).

**Command used:**

```bash
$ rip
```

**Expected behavior**
The config.toml should be included in the pip package.

**`streamrip` Configuration File (find using `rip config -o`):**
Does not exist.

**Environment**

- `streamrip` version(s): v0.6
- Python version: 3.9.5
- OS: Linux but also affects Windows and potentially MacOS

**Traceback**
```bash
Traceback (most recent call last):
  File "/usr/bin/rip", line 5, in <module>
    from streamrip.cli import main
  File "/home/Vencorr/.local/lib/python3.9/site-packages/streamrip/cli.py", line 14, in <module>
    from .config import Config
  File "/home/Vencorr/.local/lib/python3.9/site-packages/streamrip/config.py", line 20, in <module>
    class Config:
  File "/home/Vencorr/.local/lib/python3.9/site-packages/streamrip/config.py", line 36, in Config
    with open(default_config_path) as cfg:
FileNotFoundError: [Errno 2] No such file or directory: '/home/Vencorr/.local/lib/python3.9/site-packages/streamrip/config.toml'
```

**Comment by nathom** [comment]
This should be fixed in `0.6.1`.
