### ISSUE TITLE
Bug: Streamrip not working for Tidal after upgrade to 0.61 Ver

### ISSUE THREAD

**Issue by BobRock55** [nathom/streamrip#96]
## Bug Report

**Current Behavior**

 Had it working with my subscription on Tidal with no issues until I upgraded to ver 0.61 and now that is giving me an error with the same syntax that worked before.

**Command used:**

```bash
$ rip search -s tidal 'eagles' 
```

**Expected behavior**

**`streamrip` Configuration File (find using `rip config -o`):**

```toml
[downloads]
# Folder where tracks are downloaded to
folder = "/Users/nathan/StreamripDownloads"
# Put Qobuz albums in a 'Qobuz' folder, Tidal albums in 'Tidal' etc.
source_subdirectories = false
# Download (and convert) tracks all at once, instead of sequentially. 
# If you are converting the tracks, or have fast internet, this will 
# substantially improve processing speed.
concurrent = false

[qobuz]
# 1: 320kbps MP3, 2: 16/44.1, 3: 24/<=96, 4: 24/>=96
quality = 3
# This will download booklet pdfs that are included with some albums
download_booklets = true

email = ""
# This is an md5 hash of the plaintext password
password = ""
# Do not change
app_id = ""
# Do not change
secrets = []

[tidal]
# 0: 256kbps AAC, 1: 320kbps AAC, 2: 16/44.1 "HiFi" FLAC, 3: 24/44.1 "MQA" FLAC
quality = 3
# This will download videos included in Video Albums.
download_videos = true

# Do not change any of the fields below
user_id = ""
country_code = ""
access_token = ""

refresh_token = ""
# Tokens last 1 week after refresh. This is the Unix timestamp of the expiration
# time. If you haven't used streamrip in more than a week, you may have to log
# in again using `rip config --tidal`
token_expiry = ""

# Doesn't require login
[deezer]
# 0, 1, or 2
quality = 2

[soundcloud]
# Only 0 is available for now
quality = 0

[youtube]
# Only 0 is available for now
quality = 0
# Download the video along with the audio
download_videos = false
# The path to download the videos to
video_downloads_folder = ""

# This stores a list of item IDs so that repeats are not downloaded.
[database]
enabled = true
path = "/home/boban/.config/streamrip/downloads.db"

# Convert tracks to a codec after downloading them.
[conversion]
enabled = false

# FLAC, ALAC, OPUS, MP3, VORBIS, or AAC
codec = "ALAC"
# In Hz. Tracks are downsampled if their sampling rate is greater than this. 
# Value of 48000 is recommended to maximize quality and minimize space
sampling_rate = 48000
# Only 16 and 24 are available. It is only applied when the bit depth is higher
# than this value.
bit_depth = 24

# Filter a Qobuz artist's discography. Set to 'true' to turn on a filter.
[filters]
# Remove Collectors Editions, live recordings, etc.
extras = false
# Picks the highest quality out of albums with identical titles.
repeats = false
# Remove EPs and Singles
non_albums = false
# Remove albums whose artist is not the one requested
features = false
# Skip non studio albums
non_studio_albums = false
# Only download remastered albums
non_remaster = false

[artwork]
# Write the image to the audio file
embed = true
# The size of the artwork to embed. Options: thumbnail, small, large, original.
# "original" images can be up to 30MB, and may fail embedding. 
# Using "large" is recommended.

size = "large"
# Save the cover image at the highest quality as a seperate jpg file
keep_hires_cover = true

[metadata]
# Sets the value of the 'ALBUM' field in the metadata to the playlist's name. 
# This is useful if your music library software organizes tracks based on album name.
set_playlist_to_album = true
# Replaces the original track's tracknumber with it's position in the playlist
new_playlist_tracknumbers = true

# Changes the folder and file names generated by streamrip.
[filepaths]
# Create folders for single tracks within the downloads directory using the folder_format
# template
add_singles_to_folder = false
# Available keys: "albumartist", "title", "year", "bit_depth", "sampling_rate",
# and "container"
folder_format = "{albumartist} - {title} ({year}) [{container}] [{bit_depth}B-{sampling_rate}kHz]"
# Available keys: "tracknumber", "artist", "albumartist", "composer", and "title"
track_format = "{tracknumber}. {artist} - {title}"

# Last.fm playlists are downloaded by searching for the titles of the tracks
[lastfm]
# The source on which to search for the tracks.
source = "qobuz"
# If no results were found with the primary source, the item is searched for 
# on this one.
fallback_source = "deezer"

[misc]
# Check whether a newer version of streamrip is available when starting up
check_for_updates = true

# Metadata to identify this config file. Do not change.
version = "0.6.1"
```

**Environment**

- `streamrip` version(s): [e.g. v0.5.2]
- Python version: [e.g. 3.8]
- OS: [e.g. OSX 10.13.4, Windows 10]

**Traceback**
```bash
$ rip search -s tidal 'eagles' 
streamrip is up-to-date! 
Traceback (most recent call last): File "/home/xxxxx/.local/bin/rip", line 8, in <module> sys.exit(main()) File "/home/xxxxx/.local/lib/python3.8/site-packages/streamrip/cli.py", line 331, in main cli(obj={}) File "/usr/lib/python3/dist-packages/click/core.py", line 764, in call return self.main(args, *kwargs) File "/usr/lib/python3/dist-packages/click/core.py", line 717, in main rv = self.invoke(ctx) File "/usr/lib/python3/dist-packages/click/core.py", line 1137, in invoke return _process_result(sub_ctx.command.invoke(sub_ctx)) File "/usr/lib/python3/dist-packages/click/core.py", line 956, in invoke return ctx.invoke(self.callback, ctx.params) File "/usr/lib/python3/dist-packages/click/core.py", line 555, in invoke return callback(args, *kwargs) File "/usr/lib/python3/dist-packages/click/decorators.py", line 17, in new_func return f(get_current_context(), args, *kwargs) File "/home/xxxxx/.local/lib/python3.8/site-packages/streamrip/cli.py", line 178, in search if core.interactive_search(query, kwargs["source"], kwargs["type"]): File "/home/xxxxx/.local/lib/python3.8/site-packages/streamrip/core.py", line 563, in interactive_search results = tuple(self.search(source, query, media_type, limit=50)) File "/home/xxxxx/.local/lib/python3.8/site-packages/streamrip/core.py", line 489, in search client = self.get_client(source) File "/home/xxxxx/.local/lib/python3.8/site-packages/streamrip/core.py", line 269, in get_client self.login(client) File "/home/xxxxx/.local/lib/python3.8/site-packages/streamrip/core.py", line 281, in login client.login(creds) File "/home/xxxxx/.local/lib/python3.8/site-packages/streamrip/clients.py", line 549, in login self.token_expiry = float(token_expiry) 
ValueError: could not convert string to float: ''
```

**Comment by nathom** [comment]
Reset your credentials with `rip config --tidal`. Let me know if that works.

**Comment by BobRock55** [comment]
Reset helped....looks I am fine now. Thanks
