### ISSUE TITLE
It giving me error since i updated it. i don't know what is wrong. these are the lines:-

### ISSUE THREAD

**Issue by KlingonMaster** [nathom/streamrip#99]
PS C:\Users\Ankit\Downloads\streamrip-0.6.2> rip -u https://tidal.com/browse/album/52901158
streamrip is up-to-date!
Traceback (most recent call last):
  File "c:\users\ankit\appdata\local\programs\python\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\ankit\appdata\local\programs\python\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Ankit\AppData\Local\Programs\Python\Python39\Scripts\rip.exe\__main__.py", line 7, in <module>
  File "c:\users\ankit\appdata\local\programs\python\python39\lib\site-packages\streamrip\cli.py", line 414, in main
    cli(obj={})
  File "c:\users\ankit\appdata\local\programs\python\python39\lib\site-packages\click\core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\ankit\appdata\local\programs\python\python39\lib\site-packages\click\core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "c:\users\ankit\appdata\local\programs\python\python39\lib\site-packages\click\core.py", line 1646, in invoke
    super().invoke(ctx)
  File "c:\users\ankit\appdata\local\programs\python\python39\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\ankit\appdata\local\programs\python\python39\lib\site-packages\click\core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "c:\users\ankit\appdata\local\programs\python\python39\lib\site-packages\click\decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "c:\users\ankit\appdata\local\programs\python\python39\lib\site-packages\streamrip\cli.py", line 107, in cli
    core.handle_urls(kwargs["urls"])
  File "c:\users\ankit\appdata\local\programs\python\python39\lib\site-packages\streamrip\core.py", line 152, in handle_urls
    self.handle_item(source, url_type, item_id)
  File "c:\users\ankit\appdata\local\programs\python\python39\lib\site-packages\streamrip\core.py", line 166, in handle_item
    client = self.get_client(source)
  File "c:\users\ankit\appdata\local\programs\python\python39\lib\site-packages\streamrip\core.py", line 270, in get_client
    self.login(client)
  File "c:\users\ankit\appdata\local\programs\python\python39\lib\site-packages\streamrip\core.py", line 282, in login
    client.login(**creds)
  File "c:\users\ankit\appdata\local\programs\python\python39\lib\site-packages\streamrip\clients.py", line 549, in login
    self.token_expiry = float(token_expiry)
ValueError: could not convert string to float: ''
PS C:\Users\Ankit\Downloads\streamrip-0.6.2>

**Comment by nathom** [comment]
Try resetting your credentials with `rip config --tidal`

**Comment by nathom** [comment]
This should be fixed in `v0.6.2`. Run `pip3 install streamrip --upgrade` to update.
